### ISSUE TITLE
search error: pq column private does not exist

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sourcegraph/sourcegraph#11710]
- **Sourcegraph version:** 3.17.x
- **Platform information:** Ubuntu 18.04.4 [local]

I was running sourcegraph using docker locally, using sourcegraph 3.11.0, just upgraded today to 3.17.0 then to 3.17.1

#### Steps to reproduce:

1. Bootup sourcegraph locally with docker (maybe after upgrading from 3.11 :thinking: ?)
2. Try searching for anything, or access **site admin > repository status**

#### Expected behavior:
1. It should work

#### Actual behavior:
1. An error is thrown from pq, stating that `column "private" does not exist

![pq-error](https://user-images.githubusercontent.com/10640699/85692220-842c3380-b6d5-11ea-8bbd-c1e2b8f5e1bf.png)

My compose config for reference

```
version: '3.7'

services:
  sourcegraph:
    image: sourcegraph/server:3.17.1
    container_name: sourcegraph
    networks:
      - .....
    expose:
      - 7080
      - 2633
    ports:
      - '0.0.0.0:7080:7080'
      - '0.0.0.0:2633:2633'
    volumes:
      - ./path/to/config:/etc/sourcegraph
      - ./path/to/data:/var/opt/sourcegraph

networks:
  .....:

```
