### ISSUE TITLE
How to configure self signed certificates for bitbucket

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#11809]
#### Question description

I've added bitbucket server repository source. Sourcegraph was abe to retrieve a list of repos, but is **not** able to clone any repos due to self signed cert.

It would be great if sourcegraph frontend would forward cert from configuration to gitserver. Or alternatively it would be great to have instructions on how to add configuration to gitserver.

#### Additional context

Here's our configuration:
```
{
  "url": "https://bitbucket.internal",
  "token": "TOKEN",
  "username": "-sourcegraph",
  "repositoryQuery": [
    "all"
  ],
  "certificate": "-----BEGIN CERTIFICATE-----\n....\n-----END CERTIFICATE-----"
}
```

Here's what I see in logs:
```
t=2020-06-30T08:49:19+0000 lvl=dbug msg="error cloning repo" repo=bitbucket.internal/REPO err="error cloning repo: repo bitbucket.internal/REPO not cloneable: exit status 128 (output follows)\n\nfatal: unable to access 'https://bitbucket.internal/REPO.git/': SSL certificate problem: unable to get local issuer certificate\n"
```

**Comment by beyang** [comment]
@anonymousGiraffe just ran into this, too, while trying to stand up an instance talking to a Bitbucket Server instance with a self-signed TLS cert. First ran into a TLS issue and added the `certificate` field, which enabled Sourcegraph to enumerate the repositories from Bitbucket, but cloning failed with the same error.

**Comment by unknwon** [comment]
I'll check if we have any prior art on passing self-signed certificates to gitserver for other types of code hosts, if so then it should be an quick fix. Otherwise, it'll become a feature request to the core app team.

_adding this to core app support board_

**Comment by beyang** [comment]
If we aren't passing TLS certs for other code hosts through to gitserver, I'm surprised we haven't run into this more frequently for other code hosts (because I'd think self-signed certs would be relatively common for internal corp environments).

**Comment by annoymousGiraf** [comment]
> @anonymousGiraffe just ran into this, too, while trying to stand up an instance talking to a Bitbucket Server instance with a self-signed TLS cert. First ran into a TLS issue and added the `certificate` field, which enabled Sourcegraph to enumerate the repositories from Bitbucket, but cloning failed with the same error.

that's the correct user :)

**Comment by aisbaa** [comment]
For cloning from stash I had to put certificate bundle and other configuration into gitserver:

`~/.gitconfig`:
```conf
[http "https://stash.XXX.YYY.com.internal/"]
sslCAInfo = /home/sourcegraph/ca-stash-bundle.crt
sslVerify = true
```

gitserver.statufulset.yaml patch:
```
        volumeMounts:
        # stash (bitbucket)
        - mountPath: /home/sourcegraph/.gitconfig
          name: gitserver-stash-config
          subPath: gitconfig
        - mountPath: /home/sourcegraph/ca-stash-bundle.crt
          name: gitserver-stash-config
          subPath: ca-stash-bundle.crt
        - mountPath: /home/sourcegraph/.netrc
          name: gitserver-stash-config
          subPath: netrc
```
