### ISSUE TITLE
"Go to definition" broken for code host on non-standard port

### ISSUE THREAD

**Issue by rgalonso** [sourcegraph/sourcegraph#12308]
- **Sourcegraph version:** 3.17.3
- **Platform information:** Docker

#### Steps to reproduce:

1. Run self-hosted code host on non-standard port (i.e. not port 443)
2. Configure code host and Sourcegraph to speak to one another
3. Hover over code
4. Click on "Go to definition"

#### Expected behavior:

Navigate to the page on the code host that contains the symbol definition. For example, 

<pre>https://internal.mysite.com<b>:7654</b>/path/to/repo/blob/master/path/to/code#L123</pre>

#### Actual behavior:

Directed to page with address that is missing the port number. 

<pre>https://internal.mysite.com/path/to/repo/blob/master/path/to/code#L123</pre>

Note the **lack** of a port number specification in the URL.

### Specific use case

I've written the above bug description generically as it may apply to any code host running on a non-standard port, but here is my specific configuration. I am testing the Docker version of Sourcegraph with an internal self-hosted GitLab instance **running on a port other than the standard 443**. The GitLab version is 12.10.2 (Docker).

I've successfully configured the servers to talk to one another per [the GitLab documentation](https://docs.gitlab.com/ee/integration/sourcegraph.html). In Sourcegraph, I see and am able to search my repositories, and in GitLab I successfully get Sourcegraph-sourced popups when I hover over symbols. Clicking on "Find references" takes me to the appropriate page in the Sourcegraph instance as expected. However, clicking on "Go to definition" fails, because it tries to send me to the wrong page, as described above.

This could obviously be either on the GitLab or on the Sourcegraph side, but I think this may be an issue with Sourcegraph. I suspect this to be the case because I noticed that when I'm browsing the code for my repo within GitLab, the Sourcegraph URL is of the form

<pre>https://internal.mysite.com:7443/internal.mysite.com/path/to/repo@master/-/blob/path/to/code</pre>

not

<pre>https://internal.mysite.com:7443/internal.mysite.com<b>:7654</b>/path/to/repo@master/-/blob/path/to/code</pre>

(Note the addition of the port number.) 

As the FQDN to my code host and the full path to the repo are in the Sourcegraph URL, but that URL lacks a reference to my code host's non-standard port number, I think this could be the source of the issue.

**Comment by rgalonso** [comment]
I should also note that when I (temporarily) configured the GitLab instance to run on the standard port, everything worked as expected. For historical reasons though, I can't leave that as the permanent configuration.

**Comment by efritz** [comment]
@rgalonso Do you get correct hover text? Are _all_ definition operations broken? Does this port number also affect search?

**Comment by rgalonso** [comment]
This was my first time using Sourcegraph, so apologies if I'm not understanding your question fully. That said, it seemed like the hover text was correct. I was seeing the definition of the symbol in the hover text. I only tested it with a couple of different repos, but it looked like the "Go to definition" link was always broken as described above. As far as search, within Sourcegraph itself I was able to search successfully.

**Comment by efritz** [comment]
Thanks, @rgalonso.

I'd be surprised if this was a code intel issue since it depends on external services which we don't talk to directly. Is this a thing that @sourcegraph/cloud would be able to triage?

**Comment by rgalonso** [comment]
Just to look at it from another angle, what if I had two separate GitLab instances running on the same server, but on different ports? This is certainly possible. In Sourcegraph, as noted in the issue description, the URL to browse the code contains the domain where the code is hosted. If the only difference between the two code hosts in my example is in the port number, but the port number is not used in the Sourcegraph URL, there's necessarily a conflict. That's not to say that Sourcegraph isn't at least partially handling this correctly in terms of internal representation (presumably there's a database backend), but from the perspective of the URLs, it seems like there must be an issue here.

**Comment by unknwon** [comment]
> Thanks, @rgalonso.
> 
> I'd be surprised if this was a code intel issue since it depends on external services which we don't talk to directly. Is this a thing that @sourcegraph/cloud would be able to triage?

@sourcegraph/cloud needs to confirm port number is lost when passing around. Also cc @sourcegraph/web seems related to native integration / browser extension.

**Comment by keegancsmith** [comment]
Hi @rgalonso thank you for the very detailed issue description! Really appreciate it.

Just to confirm, when browsing code within sourcegraph does jump to definition work?

We do normalize repository names and strip out the port. I think this is fine, since the more readable name makes sense. The issue here is when reconstructing the URL for browsing we should be including the port.

I am unsure if this is a backend problem. If I am not mistaken the backend doesn't construct these URLs when you are browsing on the code host. My intuition tells me the fix is making the browser extension port aware when it constructs code host URLs. However, the data returned by the backend is used so the fix may lie in the backend. Someone needs to own reproducing this issue and identifing the fix. I would suspect reproducing will be the slowest part of fixing this :) @rgalonso maybe you have some magic docker compose file or something to make this easy to reproduce?

As for supporting multiple code host instances on different ports same domain, this will indeed likely break. I don't think we necessarily want to support that use case since it seems quite rare and will likely have impact on usability of more common use cases (as well as being a bit of work to fish out all the corner cases in our existing code).

**Comment by felixfbecker** [comment]
@rgalonso to confirm, you are using either the [Sourcegraph browser extension](https://docs.sourcegraph.com/integration/browser_extension) or the [code host native integration](https://docs.sourcegraph.com/integration/gitlab#gitlab-ui-native-integration)?

I would guess that this is an issue in the browser extension or the extension host. We don't expose the true repo URLs to extensions, just a `git:` URI with the repo name, which doesn't include a host. It's not surprising to me that the port gets lost somewhere. The fix would probably be https://github.com/sourcegraph/sourcegraph/issues/4278.

**Comment by rgalonso** [comment]
@keegancsmith, 

> Just to confirm, when browsing code within sourcegraph does jump to definition work?

Since this was just for test and it wasn't quite working for my use case, I already tore down that instance. So I'm not 100% sure on the answer. That said, I'm fairly certain the answer was yes.

>maybe you have some magic docker compose file or something to make this easy to reproduce?

I don't, but I'll see if I can come up with some minimal docker compose file.

---

@felixfbecker, 

> you are using either the Sourcegraph browser extension or the code host native integration?

I actually tested with both the browser extension and native integration. Again, I can't currently recreate it, but I'm reasonably certain the behavior was the same in both scenarios.

**Comment by keegancsmith** [comment]
@felixfbecker I'll let the @sourcegraph/web triage further. Happy to help on the backend side if needed.

**Comment by rgalonso** [comment]
@keegancsmith, I tried coming up with a minimal docker compose file, but didn't have much luck. To maybe you get you further along, I'm including it here anyway. (See below.) But take it with a grain of salt.

With this scenario, I never got the hover to work at all in GitLab, even when using the standard port. (True for both native integration and with browser extension.) There are some key differences though between this docker compose and the original scenario I reported the issue against.

1. In the original, GitLab and Sourcegraph were launched separately with `docker run`, not together with `docker-compose up`.
2. In the original, GitLab was running over HTTPS (albeit on a non-standard port). Using standard HTTP in the docker-compose case.
3. In the original, GitLab was associated with a valid DNS entry. In this scenario, was relying on name resolution provided by docker. Also tried modifying `/etc/hosts`, though that didn't seem to make a difference.

```
version: '3'
services:
  gitlabstandard.test.local:
  #  image: 'gitlab/gitlab-ce:latest'
    image: 'gitlab/gitlab-ce:12.10.2-ce.0'
    restart: always
    hostname: 'gitlabstandard.test.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlabstandard.test.local:80'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
    volumes:
      - '$GITLAB_HOME/gitlabstandard/config:/etc/gitlab'
      - '$GITLAB_HOME/gitlabstandard/logs:/var/log/gitlab'
      - '$GITLAB_HOME/gitlabstandard/data:/var/opt/gitlab'
  gitlabalt.test.local:
  #  image: 'gitlab/gitlab-ce:latest'
    image: 'gitlab/gitlab-ce:12.10.2-ce.0'
    restart: always
    hostname: 'gitlabalt.test.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlabalt.test.local:8081'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8081:8081'
    volumes:
      - '$GITLAB_HOME/gitlabalt/config:/etc/gitlab'
      - '$GITLAB_HOME/gitlabalt/logs:/var/log/gitlab'
      - '$GITLAB_HOME/gitlabalt/data:/var/opt/gitlab'
  sourcegraph.test.local:
    image: "sourcegraph/server:3.18.0"
    ports:
      - '7080:7080'
      - '127.0.0.1:3370:33709'
    volumes:
      - '$SOURCEGRAPH_HOME/config:/etc/sourcegraph'
      - '$SOURCEGRAPH_HOME/data:/var/opt/sourcegraph'
```
