### ISSUE TITLE
create deploy-sourcegraph to dhall record migration tool

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#13306]
This tool will take as input the deploy-sourcegraph YAML and output a structured dhall record that can be `dhall diff`'d against. Users will be able to pipe in their existing yaml, run it through this tool, and the resulting Dhall record can be iteratively diffed against the output of their https://github.com/sourcegraph/deploy-sourcegraph-dhall pipeline. Such a tool will also be useful to migrate any https://github.com/sourcegraph/deploy-sourcegraph changes over to https://github.com/sourcegraph/deploy-sourcegraph-dhall (until dhall is the source of truth). 

Note: This migration tool *will not* generate a user's pipeline customization file for them. 

```dhall
{ component-name =  { resource-kind = { resource-name = [contents] } } }
```

So for the following Kubernetes YAML resources: 

- https://github.com/sourcegraph/deploy-sourcegraph/blob/0415290e9666e55d44bf03a274226c77ec09fc4c/base/grafana/grafana.Service.yaml#L1

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: grafana
spec:
  ports:
  - name: http
    port: 30070
    targetPort: http
  selector:
    app: grafana
  type: ClusterIP
```

- https://github.com/sourcegraph/deploy-sourcegraph/blob/master/0415290e9666e55d44bf03a274226c77ec09fc4c/grafana/grafana.ConfigMap.yaml

```yaml
apiVersion: v1
data:
  datasources.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:30090
        isDefault: true
        editable: false
      - name: Jaeger
        type: Jaeger
        access: proxy
        url: http://jaeger-query:16686/-/debug/jaeger
kind: ConfigMap
metadata:
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: grafana
```

- https://github.com/sourcegraph/deploy-sourcegraph/blob/0415290e9666e55d44bf03a274226c77ec09fc4c/base/redis/redis-cache.Service.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9121"
    sourcegraph.prometheus/scrape: "true"
  labels:
    app: redis-cache
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: redis-cache
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis-cache
  type: ClusterIP
```

the migration tool will create the following Dhall record (fully-normalized): 

```dhall
{ Grafana =
  { ConfigMap.grafana =
    { apiVersion = "v1"
    , binaryData = None (List { mapKey : Text, mapValue : Text })
    , data = Some
      [ { mapKey = "datasources.yml"
        , mapValue =
            ''
            apiVersion: 1

            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus:30090
                isDefault: true
                editable: false
              - name: Jaeger
                type: Jaeger
                access: proxy
                url: http://jaeger-query:16686/-/debug/jaeger
            ''
        }
      ]
    , kind = "ConfigMap"
    , metadata =
      { annotations = None (List { mapKey : Text, mapValue : Text })
      , clusterName = None Text
      , creationTimestamp = None Text
      , deletionGracePeriodSeconds = None Natural
      , deletionTimestamp = None Text
      , finalizers = None (List Text)
      , generateName = None Text
      , generation = None Natural
      , labels = Some
        [ { mapKey = "deploy", mapValue = "sourcegraph" }
        , { mapKey = "sourcegraph-resource-requires"
          , mapValue = "no-cluster-admin"
          }
        ]
      , managedFields =
          None
            ( List
                { apiVersion : Text
                , fieldsType : Optional Text
                , fieldsV1 : Optional (List { mapKey : Text, mapValue : Text })
                , manager : Optional Text
                , operation : Optional Text
                , time : Optional Text
                }
            )
      , name = Some "grafana"
      , namespace = None Text
      , ownerReferences =
          None
            ( List
                { apiVersion : Text
                , blockOwnerDeletion : Optional Bool
                , controller : Optional Bool
                , kind : Text
                , name : Text
                , uid : Text
                }
            )
      , resourceVersion = None Text
      , selfLink = None Text
      , uid = None Text
      }
    }
  , Service.grafana =
    { apiVersion = "v1"
    , kind = "Service"
    , metadata =
      { annotations = None (List { mapKey : Text, mapValue : Text })
      , clusterName = None Text
      , creationTimestamp = None Text
      , deletionGracePeriodSeconds = None Natural
      , deletionTimestamp = None Text
      , finalizers = None (List Text)
      , generateName = None Text
      , generation = None Natural
      , labels = Some
        [ { mapKey = "app", mapValue = "grafana" }
        , { mapKey = "deploy", mapValue = "sourcegraph" }
        , { mapKey = "sourcegraph-resource-requires"
          , mapValue = "no-cluster-admin"
          }
        ]
      , managedFields =
          None
            ( List
                { apiVersion : Text
                , fieldsType : Optional Text
                , fieldsV1 : Optional (List { mapKey : Text, mapValue : Text })
                , manager : Optional Text
                , operation : Optional Text
                , time : Optional Text
                }
            )
      , name = Some "grafana"
      , namespace = None Text
      , ownerReferences =
          None
            ( List
                { apiVersion : Text
                , blockOwnerDeletion : Optional Bool
                , controller : Optional Bool
                , kind : Text
                , name : Text
                , uid : Text
                }
            )
      , resourceVersion = None Text
      , selfLink = None Text
      , uid = None Text
      }
    , spec = Some
      { clusterIP = None Text
      , externalIPs = None (List Text)
      , externalName = None Text
      , externalTrafficPolicy = None Text
      , healthCheckNodePort = None Natural
      , ipFamily = None Text
      , loadBalancerIP = None Text
      , loadBalancerSourceRanges = None (List Text)
      , ports = Some
        [ { name = Some "http"
          , nodePort = None Natural
          , port = 30070
          , protocol = None Text
          , targetPort = Some (< Int : Natural | String : Text >.String "http")
          }
        ]
      , publishNotReadyAddresses = None Bool
      , selector = Some [ { mapKey = "app", mapValue = "grafana" } ]
      , sessionAffinity = None Text
      , sessionAffinityConfig =
          None { clientIP : Optional { timeoutSeconds : Optional Natural } }
      , topologyKeys = None (List Text)
      , type = Some "ClusterIP"
      }
    , status =
        None
          { loadBalancer :
              Optional
                { ingress :
                    Optional
                      (List { hostname : Optional Text, ip : Optional Text })
                }
          }
    }
  }
, Redis.Service.redis-cache =
  { apiVersion = "v1"
  , kind = "Service"
  , metadata =
    { annotations = Some
      [ { mapKey = "prometheus.io/port", mapValue = "9121" }
      , { mapKey = "sourcegraph.prometheus/scrape", mapValue = "true" }
      ]
    , clusterName = None Text
    , creationTimestamp = None Text
    , deletionGracePeriodSeconds = None Natural
    , deletionTimestamp = None Text
    , finalizers = None (List Text)
    , generateName = None Text
    , generation = None Natural
    , labels = Some
      [ { mapKey = "app", mapValue = "redis-cache" }
      , { mapKey = "deploy", mapValue = "sourcegraph" }
      , { mapKey = "sourcegraph-resource-requires"
        , mapValue = "no-cluster-admin"
        }
      ]
    , managedFields =
        None
          ( List
              { apiVersion : Text
              , fieldsType : Optional Text
              , fieldsV1 : Optional (List { mapKey : Text, mapValue : Text })
              , manager : Optional Text
              , operation : Optional Text
              , time : Optional Text
              }
          )
    , name = Some "redis-cache"
    , namespace = None Text
    , ownerReferences =
        None
          ( List
              { apiVersion : Text
              , blockOwnerDeletion : Optional Bool
              , controller : Optional Bool
              , kind : Text
              , name : Text
              , uid : Text
              }
          )
    , resourceVersion = None Text
    , selfLink = None Text
    , uid = None Text
    }
  , spec = Some
    { clusterIP = None Text
    , externalIPs = None (List Text)
    , externalName = None Text
    , externalTrafficPolicy = None Text
    , healthCheckNodePort = None Natural
    , ipFamily = None Text
    , loadBalancerIP = None Text
    , loadBalancerSourceRanges = None (List Text)
    , ports = Some
      [ { name = Some "redis"
        , nodePort = None Natural
        , port = 6379
        , protocol = None Text
        , targetPort = Some (< Int : Natural | String : Text >.String "redis")
        }
      ]
    , publishNotReadyAddresses = None Bool
    , selector = Some [ { mapKey = "app", mapValue = "redis-cache" } ]
    , sessionAffinity = None Text
    , sessionAffinityConfig =
        None { clientIP : Optional { timeoutSeconds : Optional Natural } }
    , topologyKeys = None (List Text)
    , type = Some "ClusterIP"
    }
  , status =
      None
        { loadBalancer :
            Optional
              { ingress :
                  Optional
                    (List { hostname : Optional Text, ip : Optional Text })
              }
        }
  }
}


```

Users will be able to pipe in their existing yaml, run it through this tool, and the resulting Dhall record can be iteratively diffed against the output of their https://github.com/sourcegraph/deploy-sourcegraph-dhall pipeline. Such a tool will also be useful to migrate any https://github.com/sourcegraph/deploy-sourcegraph changes over to https://github.com/sourcegraph/deploy-sourcegraph-dhall (utill dhall is the source of truth). 

Some complications:
- There is no existing k8s label in any of our existing deploy-sourcegraph YAML that we can use to determine what the component name should be. (We can set the label going forward, however). We'll need to write logic to account for the cases where the file name isn't enough (they might have changed the file name, piped in the contents from stdin, the resource is part of YAML document, etc.) 
- We'll need to work around https://github.com/dhall-lang/dhall-kubernetes/issues/136 until that issue is fixed. This might involve manually patching the YAML before running through `yaml-to-dhall`, or pointing our tool to use types other than https://github.com/dhall-lang/dhall-kubernetes. 
- We'll also need to work around https://github.com/dhall-lang/dhall-haskell/issues/1988.
