### ISSUE TITLE
Unable to run comby in campaign spec steps because probing for shell failed

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13620]
Here's the campaign-spec.yaml:

```yaml
name: comby-go-fmt
description: Run `comby` and `go fmt`

# Find all repositories that contain a README.md file.
on:
  - repositoriesMatchingQuery: file:main.go repo:automation-testing$

steps:
  - run: 'comby -in-place fmt.Sprintf("%d", :[v]) strconv.Itoa(:[v]) .go -matcher .go -d /work -exclude-dir .,vendor'
    container: comby/comby
  - run: 'gofmt -w ./'
    container: golang:1.14-alpine

# Describe the changeset (e.g., GitHub pull request) you want for each repository.
changesetTemplate:
  title: Replacing fmt.Sprintf with strconv.Itoa
  body: This campiagn replaces `fmt.Sprintf` with `strconv.Itoa`
  branch: mrnugget/campaign-comby-go-fmt # Push the commit to this branch.
  commit:
    message: Replacing fmt.Sprintf with strconv.Iota
  published: false

```

And here's the error I get:

```
✅ Parsing campaign spec
✅ Resolving namespace
✅ Preparing container images  ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

❌ Error
   executing campaign spec: Error executing task. The log file can be found at:
   /tmp/changeset-github.com-sourcegraph-automation-testing.log747594520
   : probing image "sha256:c7bdf774c287814a4958bd175f54e598571eae161aea791df4b62e255df6f590" for shell: 2 errors occurred:
        * probing shell "/bin/bash":
   Error parsing command line:

     flag -c is an ambiguous prefix: -color, -count, -custom-matcher

   For usage information, run

     comby -help

   : exit status 1
        * probing shell "/bin/sh":
   Error parsing command line:

     flag -c is an ambiguous prefix: -color, -count, -custom-matcher

   For usage information, run

     comby -help

   : exit status 1
```
