### ISSUE TITLE
Newlines in campaign description are not rendered

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13640]
Campaign spec:

```yaml
name: thorstens-second-tracking-campaign
description: "This campaign changes all imports from

`gopkg.in/sourcegraph/sourcegraph-in-x86-asm`

to

`github.com/sourcegraph/sourcegraph-in-x86-asm`"

importChangesets:
  - repository: github.com/sourcegraph/sourcegraph
    externalIDs: [13323, 13343, 13342, 13380]
```

Rendered:

<img width="1256" alt="screenshot_2020-09-04_11 50 10@2x" src="https://user-images.githubusercontent.com/1185253/92226294-cbd4f580-eea4-11ea-9eb5-b9a8838a4be3.png">

In the database, though, the newlines seem to exist.
