### ISSUE TITLE
Allow to create multiple changeset specs in a single repository

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#14970]
A [customer](https://app.hubspot.com/contacts/2762526/company/690744415/) would like to run over the same repository multiple times to create multiple changesets (monorepo structure).

I think this makes sense to support larger repositories as well.

Challenges:
- Make sure that the backend code can deal with two changesets targetting the same repository.
- Find a way to come up with separate branch names (as they would collide otherwise).
- Come up with a good campaign spec syntax for defining the separate work directories within a repository.

Idea (not very polished):
```yaml
changesetTemplate:
  branch:
    github.com/sourcegraph/sourcegraph:
      /client/web: web-change
      /client/browser: browser-change
    github.com/sourcegraph/automation-testing: custom-branch
```
