### ISSUE TITLE
campaigns: applying `on: null`, `steps: null` throws error even though `on` and `steps` are not required

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#15045]
When using a `importChangesets` campaign, omitting `on` and `steps` is legal: https://docs.sourcegraph.com/campaigns/how-tos/tracking_existing_changesets

If the keys are simply omitted in the YAML, applying the spec works without a hitch. However, when these are set to `null`:

```
❌ Error:
   parsing campaign spec: 2 errors occurred:
        * on: Invalid type. Expected: array, given: null
        * steps: Invalid type. Expected: array, given: null
```

This is a bit of an edge case, because I'm not sure how many people will try to do this:

1. make a graphql query for an existing spec - this returns a JSON spec with `null` in values that do not exist:
```gql
            query getCampaigns($namespace:String!) {
                organization(name:$namespace) {
                  campaigns(first:99) {
                    nodes { name currentSpec { parsedInput } }
                  }
                }
              }
```
2. make changes to said campaign spec (e.g. append to `importChangesets`)
3. turn this back into YAML and `src campaign apply` it. Without replacing null values, this attempts to apply something like:
```yaml
name: release-sourcegraph-3.21.0
description: "[TEST] Track publishing of sourcegraph@3.21.0"
on: null
steps: null
importChangesets:
  - ...
changesetTemplate:
  title: ""
  body: ""
  branch: ""
  commit:
    message: ""
  published: false
```
from the original spec:
```yaml
name: release-sourcegraph-3.21.0
description: "[TEST] Track publishing of sourcegraph@3.21.0"
importChangesets:
  - ...
```
and produces the error above

also see https://github.com/sourcegraph/sourcegraph/pull/15032
