### ISSUE TITLE
campaigns: allow the target branch to be customised

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#15070]
A campaign always created a changeset against the repo's default branch at present, but there are scenarios where it may be desirable to allow customising the target branch, presumably through a new, optional `changesetTemplate` field.

**Comment by eseliger** [comment]
Another idea would be to leverage the already existing `repositories` field:


```yaml
repositories:
  - github.com/sourcegraph/sourcegraph
  - name: github.com/sourcegraph/src-cli
    branch: release
```

That way, it would also support multi-root changeset creation (monorepo support)

```yaml
repositories:
  - name: github.com/sourcegraph/src-cli
    workDirs:
      - cmd
      - internal
```
