### ISSUE TITLE
Create tutorial on how to run an openrewrite campaign in Java repositories

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#15313]
[OpenRewrite](https://github.com/openrewrite/rewrite) does "semantic code search and transformation".

It would be great to have a tutorial that shows how to run this in Java repositories.

**Comment by malomarrec** [comment]
Related: https://github.com/sourcegraph/batch-change-examples/issues/14

**Comment by mrnugget** [comment]
Direct link to the batch spec that Malo previously created: https://github.com/sourcegraph/batch-change-examples/commit/daa7001280d63fe1396dddf0b9369d1f82021f3f

**Comment by mrnugget** [comment]
This worked really well just now:

```yaml
name: run-openrewrite
description: Run Java refactor with openrewrite

on:
  - repositoriesMatchingQuery: repo:github.com/openrewrite/spring-petclinic-migration file:build.gradle fork:yes

steps:
  # Rewrite all found build.gradle files to have the openwrite plugin.
  # Add a "rewrite" recipe
  - run: |
      comby -in-place \
        "plugins { :[oldPlugins] }" \
        'plugins {
          :[oldPlugins]
          id("org.openrewrite.rewrite").version("4.3.2")
        }' \
        -f ${{ join repository.search_result_paths "," }} && \
      cat << EOF >> build.gradle
      rewrite {
          activeRecipe("org.openrewrite.java.format.AutoFormat")
      }
      EOF
    container: comby/comby
  # Run the rewrite
  - run: ./gradlew rewriteRun
    container: gradle:7.0-jdk8

changesetTemplate:
  title: Run Java refactor with openrewrite
  body: Run Java refactor with openrewrite
  branch: batch-changes/run-openrewrite
  commit:
    message: run-openrewrite
  published: false
```

<img width="881" alt="screenshot_2021-05-20_11 50 51@2x" src="https://user-images.githubusercontent.com/1185253/118959297-796c3400-b962-11eb-9533-b174adf599fa.png">
