### ISSUE TITLE
Campaign to watch gitlab group and auto-create merge requests

### ISSUE THREAD

**Issue by jglamine** [sourcegraph/sourcegraph#15890]
#### Feature request description
I'd like to have a campaign which watches the master branch of a gitlab group and automatically create a merge request if there is a git repo which is missing some data.

My use-case is that there are some common build configurations which we want to have enabled in all of our projects, but it's easy to forget to set up those configuration options when creating a new git repo. I would like to have a campaign which watches the master branch of our git repos and automatically opens a merge-request (or even automatically commits to master) to add those configuration options if they are missing.

#### Describe alternatives you've considered.

An alternative would be for me to write a bot which does this manually, but this seems like a good use-case for campaigns.

**Comment by eseliger** [comment]
Hey, great idea and use-case for a campaign :)

What would work today is setting up a periodic job (scheduled CI pipeline, for example) that runs `src campaigns apply -f spec.yaml`

with something like 

```yaml
name: ensure-recommended-ci-config
description: |
  This campaign ensures all our repos use the recommended build config values.

on:
  - repositoriesMatchingQuery: repo:^gitlab\.com\/acmecorp\/.*$ repohasfile:^\.gitlab\.yml <more extensive query to find repos that don't have your config goes here>

steps:
  - run: echo "someSetting: true" >> .gitlabci.yml
    container: ubuntu:18

changesetTemplate:
  title: Enable recommended build settings
  body: Hey there! Just a heads up this build config is recommended in our org. Please use it in your pipeline.
  branch: campaigns/add-required-build-args
  commit:
    message: Add required build args to GitLab CI config
  published: true
```

Improvements in the future that will make this even easier:
- We have https://github.com/sourcegraph/sourcegraph/issues/13405 which tracks work on making it possible to create a MR even after one has been successfully merged, for the case where the campaign added that build config, but someone deleted it later (But initially adding it would work today)
- We have https://github.com/sourcegraph/sourcegraph/issues/15083 which tracks adding a job runner to the Sourcegraph instance which would eliminate the need to set-up a CI pipeline/some scheduled job runner manually and could be triggered by a changing search result in the future

Let me know if that helps you!
