### ISSUE TITLE
Add rollout strategies for changesets

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#15901]
Defining a rollout strategy for changesets would be very powerful I think. Also, it would help with rate-limiting issues reported in https://github.com/sourcegraph/sourcegraph/issues/15892 if we had a default rollout strategy that was a little slower than "as fast as possible".

Quick spec idea:

```yaml
rolloutStrategy:
  slowRollout: 5min # Open one changeset every 5 minutes
```
```yaml
rolloutStrategy:
  github.com/*:
    slowRollout: 5min # Open one changeset every 5 minutes
```
```yaml
rolloutStrategy:
  maxOpen: 20 # only have at most 20 open changesets at the same time. if this number is lowered, existing ones are retained.
```
```yaml
rolloutStrategy:
  maxPendingCheck:
    threshold: 20 # only have at most 20 open changesets at the same time where CI checks are still reporting back.
    ignoredChecks: [codecov, chromatic]
```
