### ISSUE TITLE
src-cli: long-running containers are not killed when hitting Ctrl-C

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#16026]
A customer reports that even after https://github.com/sourcegraph/src-cli/pull/369 long running `steps` are not killed by Ctrl-C:

> Other small nitpick: there doesn’t seem to be a clean way to stop a long running `src campaign` command once it has started. The best method I’ve found so far is:
> ctrl-Z
> kill %1
> Restart Docker

**Comment by mrnugget** [comment]
@sourcegraph/campaigns I'm closing this for now since I can't reproduce this. I ran the following different `steps` definitions in our repository (all of which are long running):

```
steps:
  - run: comby -in-place 'a' 'b' .go -matcher .go -exclude-dir .,vendor
    container: comby/comby

steps:
  - run: yarn
    container: node:14.15.1

steps:
  - run: go install ./...
    container: golang:1.14.3
```

I could kill all of them without any problems. Even `sleep 30` (which is not interruptible) can be killed that way.

Again, not saying this is fixed because I have a suspicion that the `--init` fix in sourcegraph/src-cli#369 might not work with every container, but I'm closing it for now until I or someone else runs into this again and we have more debug information to reproduce. I don't want to introduce new behaviour on a suspicion without being able to confirm it.
