### ISSUE TITLE
Uploading changeset specs fails with "failed to normalize JSON: yaml: control characters are not allowed"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#16081]
Campaign spec:

```yaml
name: remove-node-modules
description: node modules fun

on:
  - repositoriesMatchingQuery: repo:automation-testing count:1

steps:
  - run: yarn add @angular/cli
    container: node:14.8

changesetTemplate:
  # [...]

```

that crashes `src-cli` with the following error:

```
⠧  Sending changeset specs

❌ Error:
   GraphQL errors: 1 error occurred:
        * {
     "message": "failed to normalize JSON: yaml: control characters are not allowed",
     "path": [
       "createChangesetSpec"
     ]
   }

```

**Comment by mrnugget** [comment]
@eseliger and I could reproduce the error with the following campaign spec that puts a `node_modules` folder in the diff:

```yaml
steps:
  - run: yarn add @angular/cli
    container: node:14.8
```

We then extracted the diff and could reproduce the parsing error in a small Go script.

I then extracted the diff with `cat bad_input.json| jq '.commits[0].diff' -r > bad_diff.patch` and ran the following script to determine on which file the parsing breaks:

```go
func parseFileDiff() {
	input, err := ioutil.ReadFile("bad_diff.patch")
	if err != nil {
		log.Fatal(err)
	}

	fileDiffs, err := diff.ParseMultiFileDiff(input)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("len(fileDiffs)=%d\n", len(fileDiffs))

	for i := 0; i < len(fileDiffs); i++ {
		diffsToParse := fileDiffs[i]

		printed, err := diff.PrintFileDiff(diffsToParse)
		if err != nil {
			log.Fatal(err)
		}

		s := struct {
			Commits []struct {
				Diff string
			}
		}{
			Commits: []struct {
				Diff string
			}{
				{
					Diff: string(printed),
				},
			},
		}

		marshaled, err := json.Marshal(s)
		if err != nil {
			log.Fatal(err)
		}

		_, err = yaml.YAMLToJSONCustom(marshaled, yamlv3.Unmarshal)
		if err != nil {
			log.Printf("error for filediff %d: %s. diff=%q\n", i, err, printed)
		}
	}
}
```

There are 8000+ files in that diff and it breaks whenever it has to parse this file:

https://github.com/ashtuchkin/iconv-lite/blob/master/encodings/sbcs-data-generated.js
