### ISSUE TITLE
Hover in settings shows big unneded "quickfix" suggestion

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#17210]
If you hover over some incorrect user settings, you'll see this big useless quickfix box:

<img width="513" alt="Screen Shot 2021-01-12 at 3 33 55 PM" src="https://user-images.githubusercontent.com/888624/104382599-a22f7900-54eb-11eb-8c30-d1b0954a06d5.png">

Here's an example setting:

```
{
  "search.repositoryGroups": {
    "sup": {
      "regex": "asdf"
    },
  }
}
```

I by chance know how to suppress this using CSS, because we do it for the search query bar:

```css
        .monaco-editor-hover-content {
            padding: 0.25rem;
            .status-bar { /* this suppresses the quickfix hover */
                display: none;
            }
        }
```
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/input/MonacoQueryInput.scss#L35-37

I just don't know where the CSS lives for user settings, and whether we actually use the hover for real suggestions.
