### ISSUE TITLE
Add "automatic workspace discovery" to `transformChanges`

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#17609]
(Just replicating what I wrote in Slack here so we don't lose it)

> While working on this [the ["dynamic workspace discovery"](https://github.com/sourcegraph/sourcegraph/issues/17367)] I’ve grown convinced that this “dynamic folder location discovery by using sourcegraph search” could/should also be used for `transformChanges`. In addition to directory: we could allow `rootAtLocationOf` and use the same mechanism to auto-discover the folders into which changes should be grouped.)

In more concrete terms: **in addition** to having this

```yaml
transformChanges:
  group:
    - directory: client
      branch: hello-world-client # will replace the `branch` in the `changesetTemplate`
    - directory: docker-images
      repository: github.com/sourcegraph/sourcegraph
      branch: hello-world-infra

changesetTemplate:
  branch: hello-world # This branch is the default branch and will be overwritten for each additional changeset.
  # [...]
```

we could have **something like** this:

```yaml
transformChanges:
  group:
    # Determine the directory locations using Sourcegraph search
    - rootAtLocationOf: package.json
      # Allow globbing when specifying the repository name
      in: github.com/sourcegraph/automation*
    - rootAtLocationOf: README.md
      # Stay backwards compatible:
      repository: github.com/sourcegraph/sourcegraph

changesetTemplate:
  # And we also use templating:
  branch: hello-world-${{ transformChanges.group.directory}}
  # Could also look like this:
  branch: hello-world-${{ changes.directory}}
  # [...]

```

**Comment by malomarrec** [comment]
+1, adding one more use case here:

#### Use case
In a monorepo structured by package
```
app
--- x
   |--- package-info.java
   |--- y2
         |---package-info.java
   |--- y1 
         |---package-info.java
```         
- Some, but not all subpackages have package-info.java .
- The spec should adjust to the repo structure, and the user shouldn't have to change the repo or add files to use batch changes.
- The user wants to create changesets at for a specific path level com.app.X, but not com.app.X.Y because that creates too many tiny changesets

#### Current behaviour
- Workspaces: rootAtLocationOf is not flexible enough, there is a package-info.java in all subpackages, which creates too many changesets
- transformChanges: doesn't work because it requires listing out all changesets

#### Proposed behaviour

- Add glob syntax to directory
- Add a way to capture branch name from repository path

```
  group:
    - directory: app/*
      branch: hello-world-client/* # branch will be made unique by appending path

changesetTemplate:
  branch: hello-world # This branch is the default branch and will be overwritten for each additional changeset.
  # [...]
```
