### ISSUE TITLE
[deploy-sourcegraph] redis-store deployment is broken

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1761]
_See https://github.com/sourcegraph/deploy-sourcegraph_

When deploying a clean version of deploy-sourcegraph to a fresh cluster: https://github.com/sourcegraph/deploy-sourcegraph/tree/783ef0994809433359056d71f70e2d2d066fec84 (at this time of writing), with adding the following storage class as the only diff:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sourcegraph
  labels:
    deploy: sourcegraph
provisioner: kubernetes.io/gce-pd
parameters:
 type: pd-ssd
 zones: us-central1-a
```

The `redis-store` pod ends up in a `CrashLoopBackoff` state. These are the logs from the container:

```shell
> kubectl logs redis-store-7bc57c987f-xhb6s redis                                                                                      
1:M 10 Jan 02:10:33.569 # Can't open the append-only file: Permission denied
```

The latest changes in the `redis-store` deployment blame to @slimsag: https://github.com/sourcegraph/deploy-sourcegraph/commit/45a9fedca3e4031bf5d33a792868f277a13965df#diff-c6d0fbac6c97bf05e436c5a45b128d43
