### ISSUE TITLE
RFC: campaigns: allow a single bot user to be used when reconciling

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#17919]
We should allow site admins to configure their site to push all campaign related commits through a bot user, _if they so choose_, and override the user credential config.

[productboard link](https://sourcegraph.productboard.com/roadmap/2104395-campaigns-kanban-board/features/6870699/detail)

**Comment by malomarrec** [comment]
When this ships, we need to add to the doc / FAQ:

*Can I still keep track authorship of who wrote the commit when using a bot account?*
Yes. The committer will be the bot account, and the author can be specified to be the user in the campaigns specs:
```
changesetTemplate:
...
  commit:
    message: Replacing fmt.Sprintf with strconv.Iota
    author:
      name: Lisa Coder
      email: lisa@example.com
```
Also see
https://docs.sourcegraph.com/campaigns/references/campaign_spec_yaml_reference#changesettemplate
