### ISSUE TITLE
Provide code host link to Bitbucket Cloud files

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#20819]
#### Feedback

A customer using both Bitbucket Cloud and Server has raised the issue that we don't link to the code host for BB Cloud code, just Server. I thought this was filed already but I'm not seeing it. I know we don't sync permissions from Cloud, but is it possible to add the link in the meantime? Otherwise BB Cloud's utility is reduced.

#### Customer

https://sourcegraph.slack.com/archives/C0183JV3Q0Y/p1620658863066900?thread_ts=1620425670.062500&cid=C0183JV3Q0Y

https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001XidrtAAB/view

**Comment by pdubroy** [comment]
I took a quick look at this. I was able to reproduce using `sg run enterprise-web-standalone`, with the following settings in my `sgconfig.overwrite.yaml`:

```
  enterprise-web-standalone:
    cmd: yarn workspace @sourcegraph/web serve:dev
    env:
      ENTERPRISE: 1
      WEBPACK_SERVE_INDEX: true
      SOURCEGRAPH_API_URL: https://k8s.sgdev.org
```

...then loading https://k8s.sgdev.org/bitbucket.org/pdubroysg/test.

I found that the logic that prevents the icon from appearing is caused by [this line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6dcc07ce162162fcea6e4678e6b6b6b3393b8bfb/-/blob/client/web/src/repo/actions/GoToCodeHostAction.tsx?L163&subtree=true) in GoToCodeHostAction.tsx. The `externalURLs` provided by the backend is empty:

![CleanShot 2021-07-02 at 10 35 44](https://user-images.githubusercontent.com/17293/124247197-ec4ff980-db21-11eb-84a1-a111616ab928.png)

This means that it's not something the Frontend Platform team could easily fix — it's probably best investigated by someone more familiar with our backend code host integration.
