### ISSUE TITLE
Spike: Change several branches in the same repo

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#23829]
## User problem
Some customers use long-lived branches to define versions or releases. 
A use case for batch changes is to update each of those branches, for example bumping up dependency versions or changing boilerplate code.

**Example**
`repo`: implements a function `foo`

`dependent-repo` has:
- branch: `release1` imports `repo` and uses `foo`
- branch: `release2` imports `repo` and uses `foo`
- branch: `release3` imports `repo` and uses `foo`

Use case: `foo` gets deprecated, and needs to be replaced by `foo2` in all releases in `dependent-repo`. Each branch is managed by a different team, so there needs to be one changeset per branch.

### Impacted customers
- [customer A](https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A94)

## Current state

- This is not supported today. 
- Batch Changes has most of the utilities to define such changes, including batch changes creating several branches and changeset in the same repo and templating to define unique branch names
- Batch Changes already supports changing a specific branch
- Batch Changes does **not** support changing multiple branches from the same repo

For example, this will only create a changeset on `release-2`:

```
name: multiple-branches
description: Creating changesets on multiple branches does not work

on:
  - repository: github.com/malomarrec/batch-change-testing-2
    branch: release-1
  - repository: github.com/malomarrec/batch-change-testing-2
    branch: release-2

steps:
  - run: touch hello-world.yml; cat release.yml
    container: alpine:3
    outputs:
      v:
          value: ${{step.stdout}}
          format: yaml


changesetTemplate:
  title: Multiple branches in the same repo
  body: Hello from the other siiiiiiiiiide
  branch: add-hw-${{outputs.v.release}}
  published: true
  commit:
    message: Hello, it's me.
```

## Proposed state

This spec results in two changesets:
- `branch-1` <- `add-hw-1`
- `branch-2` <- `add-hw-2`

**Comment by malomarrec** [comment]
@LawnGnome +pluson-ed this based on past experience

**Comment by eseliger** [comment]
This can be made to work, I think:
![image](https://user-images.githubusercontent.com/19534377/130307246-b323562d-7aaf-41de-961e-97ae593bf495.png)

We would just need to decide how we determine the repos. 

Example:
```yaml
on:
  # Matches automation-testing, sourcegraph, both at default branch
  - repositoriesMatchingQuery: file:README.md
  - repository: github.com/sourcegraph/sourcegraph
  - repository: github.com/sourcegraph/automation-testing
    branch: user-provided-1
  - repository: github.com/sourcegraph/automation-testing
    branch: user-provided-2
```

We could:

1. Just take all branches we find, that would include:
- sourcegraph@main
- automation-testing@main
- automation-testing@user-provided-1
- automation-testing@user-provided-2

2. Discard defaultBranches, if explicitly specified:
- sourcegraph@main
- automation-testing@user-provided-1
- automation-testing@user-provided-2

3. Overwrite the default branch with the first custom value, afterwards accumulate (really the same a above, but different reasoning):
- sourcegraph@main
- automation-testing@user-provided-1
- automation-testing@user-provided-2

4. Something entirely different?

**Comment by LawnGnome** [comment]
The challenge here feels like `repositoriesMatchingQuery` when it matches a repo _also_ matched by an explicit `repository:` statement: I think we can all agree that any repo matched by `repository` is going to be the default branch unless otherwise specified.

I'm not sure what the principle of least surprise would indicate here: does a user expect that `repository: repo.that.also/matches/a/query` would override something matched from a query, or is it additive? (Which I realise is the question you're posing, but I'm trying to think it through from a user perspective.) To me, I think I'd understand the additive case (option 1 above) was more technically correct after thinking it through, but as a neophyte user, I'd probably expect the override behaviour (option 2/3).

Another option here might be to force the user to choose: if they provide one or more `branch` fields, then they also have to specify the branch in all the `on:` children. That's probably annoying for the user, but it avoids the ambiguity.

**Comment by malomarrec** [comment]
Moving back to triage, and self-assigning. Need to decide what we do with this.

**Comment by malomarrec** [comment]
@eseliger @LawnGnome I re-read this carefully after the sync.
The behaviour should be is additive, because that's the way the current syntax work. You find repositories with `on.repositoriesMatchingQuery`, you can add some more by name, then more by `on.repositoriesMatchingQuery`, then they get de-duplicated and the change gets created.

So in my opinion, we should do the same here, leading to option 1 "take all branches we find".

- That addresses the use case described in this ticket (name all the branches).
- That doesn't break any current behaviour
- It's simple to explain: collect all the `(repo, branch, path)` matches (we call that a workspace), de-duplicate, run on each of them separately.

**Comment by malomarrec** [comment]
How about this use case
```
on:
  - repositoriesMatchingQuery: repo:github\.com/sourcegraph/* rev:*refs/heads/dev* foo
  - repositoriesMatchingQuery: repo:github\.com/sourcegraph/* rev:*refs/heads/release-1* foo
  - repositoriesMatchingQuery: repo:github\.com/sourcegraph/* rev:*refs/heads/release-2* 
  - repository: github.com/sourcegraph/automation-testing
    branch: user-provided-1
```

**Comment by LawnGnome** [comment]
Option 4, as discussed in the sync: explicit `repository:` statements override `repositoriesMatchingQuery:`. In the event multiple `repository` statements are defined with the same repo, only the last one is used. To support multiple branches, the `branch:` field can be a string _or_ a list, and can also be named `branches:`.

Separate to the above, I think we all agree some sort of `exclude:` statement would also be beneficial in the longer run, since that also addresses a SSBC UI issue.

I change my vote to option 4, with option 3 as my second choice.

**Comment by mrnugget** [comment]
> How about this use case

I'd say that's exactly why we have `repository:`.

**Comment by LawnGnome** [comment]
> How about this use case

What I just said in the sync: I think, if you have queries that are that specific, you probably know they match the exact set of repositories and branches that you want, and `repository:` overriding the query results won't matter because you aren't going to add `repository:` statements matching the repos in the search results anyway.

**Comment by malomarrec** [comment]
How do I do the following?

1. List out branches that I want to modify in a given repository?

```
on:
  - repository: github.com/sourcegraph/automation-testing
    branches: [user-provided-1, user-provided-2]
```

2. List out branches that I want to modify in a given repository, and mix and match with a query?

```
on:
  - repositoriesMatchingQuery: file:README.md
  - repository: github.com/sourcegraph/automation-testing
    branches: [user-provided-1, user-provided-2]
```
If the query returns the main branch of `sourcegraph/automation-testing`, it is overridden by the set of branches named explicitly.

3. Modify all the branches in the list of repositories?
Out of scope. Would be cool to support something like:

```
on:
  - repositoriesMatchingQuery: repo:github\.com/sourcegraph/* rev:*refs/heads/dev* foo
  - repositoriesMatchingQuery: repo:github\.com/sourcegraph/* rev:*refs/heads/release-1* foo
  - repositoriesMatchingQuery: repo:github\.com/sourcegraph/* rev:*refs/heads/release-2* 
```
