### ISSUE TITLE
Env variables are not passed to containers

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#23968]
- **Sourcegraph version:** 3.30.3
- **src-cli version:** reproduced on 3.28 and 3.30.5

#### Steps to reproduce:

1. run `HELLO_USER=malo`
2. run `src batch preview -f hello-name.yml`

Spec:

```
name: parametrize
description: Parametrizing changesets

on:
  - repository: github.com/malomarrec/batch-change-testing-2
    branch: release-1

steps:
  - run: echo Hello $HELLO_USER >> hello.md
    container: alpine:3
    env:
      - HELLO_USER

changesetTemplate:
  title: Add hello from me
  body: Hello from the other siiide
  branch: add-hello-name
  published: true
  commit:
    message: Hello, it's me.
 ```
 
#### Expected behavior:

A diff with "hello malo"
https://docs.sourcegraph.com/batch_changes/references/batch_spec_yaml_reference#examples-7

#### Actual behavior:

A diff with "hello"
