### ISSUE TITLE
codeintel: Apex support

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#25238]
- [x] (already supported) `lang:Apex` filter
- [x] Find an open-source `.tmLanguage` or `.sublime-syntax` file (can't use [this](https://github.com/joeferraro/MavensMate-SublimeText/blob/master/sublime/lang/Apex.sublime-syntax) because it's GPL?)
- [x] Merge https://github.com/slimsag/Packages/pull/14
- [x] Merge https://github.com/slimsag/syntect/pull/11
- [x] Merge https://github.com/sourcegraph/code-intel-extensions/pull/686
- [x] Merge https://github.com/sourcegraph/zoekt/pull/158
- [x] Merge https://github.com/sourcegraph/sourcegraph/pull/25268
- [x] Merge https://github.com/sourcegraph/sourcegraph/pull/25370
- [x] Merge https://github.com/sourcegraph/sourcegraph/pull/25371

**Comment by tjdevries** [comment]
An open question I have (perhaps should be asked in slack) is when I'm reading about Apex, it seemed that there may be some other supporting files that are not Apex files, but are associated with Apex work (like some special html looking stuff).

For example:
- https://github.com/neowit/vim-force.com/blob/master/ftdetect/vim-force.com.vim

**Comment by chrismwendt** [comment]
Notes from pairing: `apex,cls,trigger` seems to cover all the Apex files, and others look like HTML.

As a point of comparison, GitHub's linguist project currently only lists `.cls` for Apex, and doesn't have aura (which is one of the files that appears to be associated with Apex). https://github.com/github/linguist/blob/971e152fabca12e0ad386833eecb7b15e312a09f/lib/linguist/languages.yml#L316-L325

```yaml
Apex:
  type: programming
  color: "#1797c0"
  extensions:
  - ".cls"
  tm_scope: source.java
  ace_mode: java
  codemirror_mode: clike
  codemirror_mime_type: text/x-java
  language_id: 17
```
