### ISSUE TITLE
sg: Build in support for downloading and using binaries

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#25438]
Multiple commands in `sg.config.yaml` follow the same pattern:

1. Download a binary based on environment variables
2. Unzip the download
3. Move it into `.bin`

Example: `caddy`.

https://github.com/sourcegraph/sourcegraph/blob/548ec915b34e79d44334155a2efb721e8a7ba5b9/sg.config.yaml#L256-L274

We could build that functionality right into `sg` and reduce the amount of shell code in `sg.config.yaml` (and provide better output/debugging for the install process).

For example, we could have something like this:

```yaml
  caddy:
    ignoreStdout: true
    ignoreStderr: true
    cmd: .bin/caddy run --watch --config=dev/Caddyfile
    installBinary:
      url: https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_${SG_OS}_amd64
      binaryName: caddy
    env:
      CADDY_VERSION: 2.3.0
```
