### ISSUE TITLE
deployment: incorrect SYMBOLS_CACHE_SIZE_MB setting when using resourceFieldRef

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#26283]
The SYMBOLS_CACHE_SIZE_MB setting in the [symbols deployment](https://github.com/sourcegraph/deploy-sourcegraph/blob/60386844481f5181edb7f4c1cb33adfeb6316fe0/base/symbols/symbols.Deployment.yaml) is incorrectly auto-calculated from an ephemeral storage resource size. The variable expects MB but the requests are provided in bytes.

Adding a divisor will resolve this issue:
```
            resourceFieldRef:
              containerName: symbols
              resource: requests.ephemeral-storage
              divisor: "1M"
```
