### ISSUE TITLE
Enable yamllint (or other YAML validation software) on infrastructure components 

### ISSUE THREAD

**Issue by danieldides** [sourcegraph/sourcegraph#28577]
YAML has a lot of flexibility regarding strings and it can cause confusion and [misconfigurations](https://github.com/sourcegraph/sourcegraph/issues/27387). Utilizing some sort of linter to validate YAML documents and enforce strict consistency could help reduce some of these issues. 

For example:
```yaml
pg_sg_migration:
  query: 'SELECT dirty::int as status FROM codeintel_schema_migrations'
  master: true
  metrics:
    - status:
        usage: GAUGE" # missing the closing quote
        description: Whether the migration applied successfully
```
Could be detected and avoided using [`yamllint`](https://github.com/adrienverge/yamllint) and a minimal configuration:
```yaml

---
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  quoted-strings: enable
```

```
$ yamllint -c .yamllint config/05_codeintel_migration.yaml
config/05_codeintel_migration.yaml
  13:16     error    string value is not quoted with any quotes  (quoted-strings)
  14:22     error    string value is not quoted with any quotes  (quoted-strings)

```
