### ISSUE TITLE
transformChanges and workspaces don't really work together

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#29266]
This is from https://github.com/sourcegraph/customer/issues/599, but was [a known issue anyway](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6e51851fbb8a3457756853e278844d130f2d8db4/-/blob/lib/batches/changeset_specs.go?L97-99): workspaces that would result in the same repo getting multiple branches with names set by `transformChanges` are currently unsupported because the transformation occurs _after_ the changeset specs are built and validated.

Given #28246, I'm unsure if we actually want to fix this — it really depends on whether we intend to support `transformChanges` in the longer term as a non-experimental feature.

**Comment by LawnGnome** [comment]
An example spec that demonstrates the problem:

```yaml
name: workspace-transform
description: Use workspaces and transformChanges together
on:
  - repository: github.com/sourcegraph-testing/mono-rocks
workspaces:
  - rootAtLocationOf: package.json
    onlyFetchWorkspace: false
changesetTemplate:
  branch: ABC-123
  title: do-something
  body: This change does something
  commit:
    message: Do Something
steps:
  - run: |
      echo Hello world! | tee -a README.md
    container: alpine:3
transformChanges:
  group:
    - directory: parent/child1
      branch: ABC-123-child1
    - directory: parent/child2
      branch: ABC-123-child2
    - directory: parent/child3
      branch: ABC-123-child3
```
