### ISSUE TITLE
Unable to get chrome extension working on private gitlab.com typescript repro

### ISSUE THREAD

**Issue by thinktopdown** [sourcegraph/sourcegraph#3033]
- **Sourcegraph version:**
3.2.0

- **Platform information:** 
macOS 10.14
chrome Version 73.0.3683.86 (Official Build) (64-bit)
srcgrph ext v19.3.22.1110
Docker version 18.09.0, build 4d60db4

#### Steps to reproduce:

1. setup local srcgraph instance and typescript server via docker compse

```
version: '3'
services:
  sourcegraph:
    ports:
    - "7080:7080"
    - "2633:2633"
    volumes:
    - ~/.sourcegraph/config:/etc/sourcegraph
    - ~/.sourcegraph/data:/var/opt/sourcegraph
    image: sourcegraph/server:3.2.0
  typescript-lang:
    ports:
      - "7081:8080"
    image: sourcegraph/lang-typescript
```

2. configure srcgraph instance to work on gitlab.com using a personal access token.

3. enable private repos

4. configure global settings for ts lang server
{
"typescript.serverUrl": "ws://localhost:7081",
"typescript.sourcegraphUrl":"http://sourcegraph:7080"
}

4. verify "find refs/jump def" at http://localhost:7080

5. open chrome. add srcgraph extension.

6. give srcgrph chrome ext access to https://gitlab.com/*

7. connect srcgrph chrome ext to http://localhost:7080

8. open private PR on gitlab.com for enabled repro. 

#### Expected behavior:

- see "jump def/find refs" popup for my private gitlab repro

#### Actual behavior:

- doesn't appear. can't seem to find any logs...
