### ISSUE TITLE
executors: Batch Changes hooks

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#31532]
Webhooks are great for integrating existing systems into each other, like making Sourcegraph re-fetch a repo on a commit, integrating code monitoring with Slack, or even changesets being published or merged into some notification system. 
For 1-off things, this can be a bit tedious to set up though. You need a webserver running somewhere accessible by the Sourcegraph instance, do a security handshake, handle errors, logs, etc. yourself, and more of these things. 
When I really _just want to run a very specific command_ for this very batch change, the overhead of creating such a service, setting it up properly and such can sometimes outweigh the benefit over running something manually, especially for medium-sized batch changes.

Another idea, in addition to webhooks, could be adding hooks directly to the spec, and using SSBC executors to treat it as _just another step to execute_:

```yaml
name: test-reviewer
on:
  - repositoriesMatchingQuery: r:automation-testing$

steps:
  - run: printf "\n(c) Copyright Sourcegraph 2013-2020." | tee -a $(find -name README.md)
    container: alpine:3.13

##### INTERESTING BIT HERE ####
hooks:
  postPublish:
    run: |
      CODEOWNER=${corp-cli get codeowner ${{ repository.name }} ${{ diff.paths }})
      jira-cli create ticket ${{ changeset.title }} --assignee $CODEOWNER
    container: mycorp-postruncontainerthingy:1.0.0

changesetTemplate:
  title: Test reviewers
  branch: batches/es/test-reviewer
  commit:
    message: Test reviewers
```

It could, just as elsewhere, accept templating, run a command in a given container and therefore just utilize the executors we already got. Just an idea, and we didn't know where else to track it so adding it here as a comment. This does not change the scope of the spike, however.

_Originally posted by @eseliger in https://github.com/sourcegraph/sourcegraph/issues/26790#issuecomment-979384127_
