### ISSUE TITLE
Mount files on steps containers for local runs(minimal)

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#31790]
Make it possible for users to add files located alongside the spec to the batch change, when running locally using `src-cli`. In this first iteration, doing so is not represented in the batch changes UI at all so this ticket should no involve any UI work

```
steps:
   - run cat path/to/file.txt
   mount: 
      - path: local/path/to/file.text
         mountpoint: path/to/file.txt
```
We will limit mountable paths to ./ and down, so nothing inside the expected working directory ends up mounted.
