### ISSUE TITLE
Hardcoded DB & user names

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#31835]
# Customer request to enable them to make the move to using Helm to deploy Sourcegraph.

Customer is: https://github.com/sourcegraph/accounts/issues/8263 (name can only be seen by Sourcegraph org members).

## Description:
> DB & user must use hardcoded values when using AWS cloudformation.
> 
> `docker run [...] -e PGHOST=[psql1.mycompany.org](https://psql1.mycompany.org/) -e PGUSER=sourcegraph -e PGPASSWORD=secret -e PGDATABASE=sourcegraph -e PGSSLMODE=require -e CODEINTEL_PGHOST=[psql2.mycompany.org](https://psql2.mycompany.org/) -e CODEINTEL_PGUSER=sourcegraph -e CODEINTEL_PGPASSWORD=secret -e CODEINTEL_PGDATABASE=sourcegraph-codeintel -e CODEINTEL_PGSSLMODE=require sourcegraph/server:3.36.3`
> 
> [https://docs.sourcegraph.com/admin/external_services/postgres#general-recommendations](https://docs.sourcegraph.com/admin/external_services/postgres#general-recommendations)
> 
> The customer would like to use their own custom values for DB & User.

## Impact:
>The customer must use hardcoded values and not their desired custom values.

## Useful links:
- [Link to Salesforce Product Gap](https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap__c/a1B5b00000L9YRUEA3/view) (for internal ref only)

**Comment by caugustus-sourcegraph** [comment]
@superhsu 
Can we get some more details about the request? I think there's some missing information here since it talks about Cloudformation and uses the server image, which doesn't have anything to do with helm.

My guess is that the request is to use an external database set up via Cloudformation, and they want to use a custom database name and username instead of the defaults. Is that correct? Are there any other considerations?

This is already possible in the helm chart - we provide a basic [example here](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/examples/external-databases/override.yaml) how to override settings for an external database. We can improve that example to show the PGUSER/PGDATABASE variables.

**Comment by nickstapler-wk** [comment]
Hey @caugustus-sourcegraph
We are creating our databases in cloudformation
```
CodeIntelRDSDatabaseName:
    Description: The name of the code-intel's DB instances.
    Type: String
    Default: sourcegraph-codeintel 	<-
CodeIntelDBCluster:
    Type: AWS::RDS::DBCluster
    DependsOn: CodeIntelDBClusterParameterGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BackupRetentionPeriod: !Ref RDSBackupRetentionPeriod
      DatabaseName: !Ref CodeIntelRDSDatabaseName.    <-
    ...
```
In this case, i asked if we needed to use the value "sourcegraph-codeintel" for the dbname that was seen in the other external db examples.

With this current db name value the stack creation fails with:

>DatabaseName must begin with a letter and contain only alphanumeric characters. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue;
