### ISSUE TITLE
Consider removing default ingress annotation from helm

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#32479]
## The problem

Let's say I want to configure Ingress to use external lb on GCP and I have the following override

```yaml
frontend:
  ingress:
    ingressClassName: gce
```

GKE actually won't be able to pick up the ingress object and create an external lb for it.

Why? Our default ingress annotations set ingress class to `nginx` (`kubernetes.io/ingress.class: nginx`) https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/values.yaml#L265

We can workaround it by overriding the annotations instead of using the `.ingressClassName` value (you can't have both)

```yaml
frontend:
  ingress:
    annotations:
      kubernetes.io/ingress.class: gce
```

I think this caused unexpected results to clients that deploy stuff on cloud vendors that provides their own ingress controller (other than `nginx`). 

## Workaround

```yaml
frontend:
  ingress:
    annotations:
      kubernetes.io/ingress.class: null
    ingressClassName: gce
```

## Implementation

Remove the default `ingress.class` ingress annotation

Also need to reflect the change in this override.yaml
