### ISSUE TITLE
Improve database.conf override

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#32700]
In our helm chart, the users have to either use the pgsql.conf we ship by default, or they have to "fork" our `pgsql.ConfigMap.conf` and configure `pgsql.existingConfig=<some configmap name>`

Whenever we make changes to the default `pgsql.conf`, we rely on communicating with users through our changelog, and al lot of people don't read.

## Proposal

We can change the behaviour from override to extend.

> the name `additionalConfig` is subject to change, I just come up with something

`values.yaml`
```yaml
  pgsql:
    additionalConfig: |
      max_connections = 500
```

`pgsql.ConfigMap.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    description: Configuration for PostgreSQL
  labels:
    deploy: sourcegraph
    app.kubernetes.io/component: pgsql
  name: pgsql-conf
data:
  postgresql.conf: |
    # existing stuff
    # additional stuff
    # we put additionalConfig at the end because the stuff at the bottom will take higher precedence
    # I think this is the desire behaviour?
    {{- .Values.pgsql.additionalConfig }}
```

By doing so, for users who customize DB config can do so in a way without risk missing out from future upgrades. 

A good example would be the recent timescaledb -> vanilab pg change. If users choose to extend config instead of overriding it, the upgrade experience would have been smoother.

Also, the benefit of using helm is users get to create less dangling k8s resources to run Sourcegraph.
