### ISSUE TITLE
Per batch change control for pushing to forks

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#33110]
### Context

We have recently introduced the possibility to push branches created by Batch Changes to a fork of the repository, rather than the repository itself. 

This was built as an [MVP](https://github.com/sourcegraph/sourcegraph/issues/17879) to address:

- Most users do not have write permission on all repositories, so branch creation fails for them (https://github.com/sourcegraph/accounts/issues/544)
- Some companies _enforce_ that all PRs created by automation are opened on forks. (https://github.com/sourcegraph/accounts/issues/565, https://github.com/sourcegraph/accounts/issues/4778 )

### Next problems

The current MVP state is the end state solution for companies that mandate using forks for all repositories. It's not a fully mature solution though for users that don't have write-permission on all repositories and only want to use forks in some cases:
- not all users want to use forks
- a given user wants to use forks, but only for a specific batch change
- a user wants to create forks, only if they're missing permissions

### Impacted customers

- https://github.com/sourcegraph/accounts/issues/6859 ([insight](https://sourcegraph.productboard.com/feature-board/2104383-batch-changes/notes/22661534))

### Next iteration

Make using forks a parameter of the batch change itself.
There could be a `useForks:true` (default: `false`) in the batch spec

**Comment by malomarrec** [comment]
I was curious to understand what was preferrable: have a `fork` attribute in the spec, or have a "smarter" behaviour, where batch changes would automatically create forks if it encounters a permission error. An interesting argument at https://github.com/sourcegraph/sourcegraph/issues/33110 was:
> MO it’d be preferable to have a fork attribute. orgs should be using one pattern or the other. If they’re using a mixed model, the fork attribute might encourage them into one camp or the other

**Comment by eseliger** [comment]
Agree with the sentiment.

**Comment by LawnGnome** [comment]
I think it should be an explicit attribute in the spec, and I'd even go a step further and say it should be the target repo name in a form we can parse, not just a boolean. I'd go with something like these options (spitballing, obviously — only one `fork` would be valid, but just trying to show the range of options I think we should support):

```yaml
changesetTemplate:
  fork: foo           # forks into the `foo` organisation/user, assuming the
                      # user has permission
  fork: LawnGnome     # forks into the user's namespace as well (assuming the
                      # user is LawnGnome), but explicitly by name
  fork: user          # forks into the user's namespace, same as the current
                      # switch
```

So, basically, `fork` would be a string pointing to the owner to fork into, or the magic string `user`, which corresponds to the current user. This allows us to support use cases where the fork goes into a team or company organisation, rather than an individual user's organisation.

Bonus side note: I'd also like us to consider (eventually) adding a parallel `remote` entry to provide an escape hatch for weird edge cases we can't support with forks, which would be particularly useful on code hosts that don't support forking (not an issue today, but who knows where we're going). I could see that looking like this:

```yaml
changesetTemplate:
  remote: foo/bar                   # pushes to an existing remote that we
                                    # won't attempt to fork, but it is assumed
                                    # already exists, using the code host of
                                    # the target repo to construct a push URI
  remote: git@github.com:foo/bar    # pushes to an explicit remote URI
```
