### ISSUE TITLE
Dogfood: Instead of using renovate, use batch changes to update image tags from CI

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#33659]
From this [thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1649412415314809):

```
name: update-sourcegraph

on:
  - repository: github.com/sourcegraph/deploy-sourcegraph-k8s
  - repository: github.com/sourcegraph/deploy-sourcegraph-cloud

steps:
  - command: update-image $IMAGE_TAG
    image: sourcegraph/image-updater:latest
    env: [IMAGE_TAG]

changesetTemplate:
  title: Update Sourcegraph to ${{ IMAGE_TAG }}
  publish: true
```
