### ISSUE TITLE
404 when using `src batch remote`

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#33696]
####

CLI version

```
malo@sourcegraph.com@Malos-MacBook-Pro-2 ~ % brew info src-cli
sourcegraph/src-cli/src-cli: stable 3.38.0
Sourcegraph CLI
https://sourcegraph.com/
/opt/homebrew/Cellar/src-cli/3.38.0 (6 files, 18.0MB) *
  Built from source on 2022-04-09 at 12:25:51
From: https://github.com/sourcegraph/homebrew-src-cli/blob/HEAD/Formula/src-cli.rb
```

#### Steps to reproduce

1. Copy the file below
1. Set `SRC_ENDPOINT=https://demo.sourcegraph.com/` and a `SRC_ACCESS_TOKEN`
1. Run `src login`
1. Run `src batch remote -f comby-go-refactor.batch.yml`

comby-go-refactor.batch.yml

```
name: comby-go-fmt
description: Run `comby` and `go fmt`

# Find all repositories that contain a README.md file.
on:
  - repositoriesMatchingQuery: lang:go fmt.Sprintf("%d", :[v]) patterntype:structural

steps:
  - run: comby -in-place 'fmt.Sprintf("%d", :[v])' 'strconv.Itoa(:[v])' ${{ join repository.search_result_paths " " }}
    container: comby/comby
  - run: goimports -w ${{ join previous_step.modified_files " " }}
    container: unibeautify/goimports

# Describe the changeset (e.g., GitHub pull request) you want for each repository.
changesetTemplate:
  title: Replacing fmt.Sprintf with strconv.Itoa
  body: This campiagn replaces `fmt.Sprintf` with `strconv.Itoa`
  branch: batch-changes/comby-go-fmt # Push the commit to this branch.
  commit:
    message: Replacing fmt.Sprintf with strconv.Iota
```

#### Expected result

A batch change execution link

#### Output

<img width="765" alt="image" src="https://user-images.githubusercontent.com/25070988/162568755-95fe6f36-db27-4e77-a69d-b5febf125543.png">

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/25070988/162568764-dfc91bf0-18ef-441d-8e29-24b5a7fafc71.png">

This persists even when waiting a few minutes.
Running the same operation directly from the UI works.
