### ISSUE TITLE
[deploy-sourcegraph] - Incorrect storage size on generated template for minikube

### ISSUE THREAD

**Issue by nrolando46** [sourcegraph/sourcegraph#34548]
Hi Sourcegraph Team,

I am doing a POC of sourcegraph in a local minikube instance.  While following this [guide](https://handbook.sourcegraph.com/departments/support/process/enablement/minikube/) I was running into an issue with my "storage-provisioner" pod constantly crashing and my other pods wouldn't start...

I reviewed the deployment files and noticed that the "apps_v1_statefulset_gitserver.yaml" that was generated from the `./overlay-generate-cluster.sh minikube generated-cluster` script had 200g as the `volumeClaimTemplates` on 
```
 volumeClaimTemplates:
  - metadata:
      name: repos
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
      storageClassName: standard 
```

I then changed it to `storage: 10Gi`  and all my pods started running. 

Not sure if this was the solution but it's something to raise.

Thank you,

Nelson M. 

/cc @sourcegraph/delivery
