### ISSUE TITLE
Add kustomization example for changing to a private registry

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#36117]
A common use case for kustomize is to change image references to a private registry. We could provide an example, or perhaps an overlay, that demonstrates a maintainable way to run this operation.

For example:
```
images:
  - name: index.docker.io/sourcegraph/alpine-3.14
    newName: custom-registry-url/sourcegraph/alpine-3.14
    newTag: release-3.40.0
```
