### ISSUE TITLE
Investigate workspace mode BIND for macOS

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#36598]
I wonder whether we can make bind workspace mode the default on Mac soon, once the new virtiofs is on by default.
volume mode has a non-trivial overhead for detecting the workspace user ID to set permissions correctly and has to copy the files from the host into the temporary docker volume.
Not counting that, the runtime difference in a very poorly run experiment is still almost negligible nowadays, installing create react app (heavy npm dependency tree) takes 1:09 using bind and 1:05 using volume. Of course, this is also subject to network speed and I did not perform many runs, but so far it looks promising. We can of course keep volume mode as an explicit flag for those who run into an edge case.

**Comment by BolajiOlajide** [comment]
Ran a benchmark using [hyperfine](https://github.com/sharkdp/hyperfine) for 300 runs of `batch preview`

```sh
hyperfine --warmup 3 --runs 300 \
    "src batch preview -workspace bind -cache /tmp/src-test-cache1 -f 2batch.yaml" \
    "src batch preview -workspace volume -cache /tmp/src-test-cache2 -f 2batch.yaml" \
    --export-markdown benchmark.md
```

## Batch Spec

```yaml
name: nv
description: Add Hello World to READMEs

# This is your query from search
on:
  - repositoriesMatchingQuery: context:global repo:^gitlab\.com/sourcegraph-testing/zap$ file:README.md patternType:literal

steps:
  - run: IFS=$'\n'; echo Hello World | tee -a $(find -name README.md)
    container: ubuntu:18.04

# Describe the changeset (e.g., GitHub pull request) you want for each repository.
changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: bo-run-openrewrite
  commit:
    message: Append Hello World to all README.md files

```

| OS Arch | Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|---:|
| MacOS (amd) | `src batch preview -workspace bind -cache /tmp/src-test-cache1 -f 2batch.yaml` | 1.988 ± 0.312 | 1.764 | 6.961 | 1.00 |
| MacOS (amd) | `src batch preview -workspace volume -cache /tmp/src-test-cache2 -f 2batch.yaml` | 2.288 ± 0.687 | 1.964 | 7.751 | 1.15 ± 0.39 |

**Comment by eseliger** [comment]
Are you sure it ran over the workspace the other 299 times? Without `-clear-cache` or a new cache dir for every run, src-cli should find a match and not run execution a second time 🤔 

Also, the big problem with bind mode was IO, this example batch spec doesn't do a lot of IO. Maybe try to run yarn in the sg/sg repo to compare the two?

**Comment by BolajiOlajide** [comment]
Oh I'm not done yet. Just added this here so I can have access to the commands on my personal laptop.

**Comment by eseliger** [comment]
Ah, all good then!

**Comment by eseliger** [comment]
What's the status of this ticket?

**Comment by BolajiOlajide** [comment]
I'll wrap this up today. I've been focused on other things - I just need to run the batch spec that'll affect more files.

**Comment by BolajiOlajide** [comment]
### Docker version
4.10.1

![CleanShot 2022-07-17 at 07 17 54@2x](https://user-images.githubusercontent.com/25608335/179386548-ae5fc99b-eea7-463a-be61-46294c85c982.png)


Ran a benchmark using [hyperfine](https://github.com/sharkdp/hyperfine) for 300 runs of `batch preview`

```sh
hyperfine --warmup 1 --runs 300 \
    "src batch preview -workspace bind -clear-cache -f batch.yaml" \
    "src batch preview -workspace volume -clear-cache -f batch.yaml" \
    --show-output \
    --export-markdown benchmark.md
```

### Batch Spec

```yaml
name: pin-colors-3
description: Force colors to use 1.4.0 to avoid vulnerability

# This is your query from search
on:
#   - repositoriesMatchingQuery: context:global file:package.json fork:yes patternType:structural
  - repositoriesMatchingQuery: file:package.json fork:yes repo:^github.com/(sourcegraph|sgtest) count:50

steps:
  - run: |
      for result in "${{ join repository.search_result_paths " " }}"; do
        python /tmp/script "${result}";
      done;
    container: python:3-slim
    files:
      /tmp/script: |
        import json
        import sys
        try:
            package = None
            files = sys.argv[1]

            for file in files.split(' '):
            	# Look for colors in package-lock to catch transitive dependencies, add resolutions in package.json
                file = file.replace('package-lock.json', 'package.json')
                with open(file) as f:
                    package = json.loads(f.read())
                    if 'resolutions' in package:
                        package['resolutions']['colors']="1.4.0"
                    else:
                        package['resolutions'] = {"colors":"1.4.0"}
                with open(file, "w") as f:
                    f.write(json.dumps(package, indent=2))
        except Exception as e:
            print("No-op:error {}".format(e))
  
changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: hello-world # Push the commit to this branch.
  commit:
    message: Append Hello World to all README.md files
```

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `src batch preview -v -workspace bind -clear-cache -f batch.yaml` | 13.612 ± 0.293 | 13.103 | 14.316 | 1.00 |
| `src batch preview -v -workspace volume -clear-cache -f batch.yaml` | 14.436 ± 0.195 | 14.180 | 14.999 | 1.06 ± 0.03 |

#### Summary

```
  'src batch preview -v -workspace bind -clear-cache -f batch.yaml' ran
    1.06 ± 0.03 times faster than 'src batch preview -v -workspace volume -clear-cache -f batch.yaml'
```

Using the `bind` mount is faster than `volume`. This benchmark includes running a preview of the batch spec above 300 times on my machine for the different workspace options:

* `bind`
* `volume`

cc @sourcegraph/batchers

**Comment by eseliger** [comment]
Nice, that looks promising!

Can you try something more even IO intensive, like running `yarn` in our main repo? I think this example doesn't fully exercise the different FS backends to the max.

**Comment by eseliger** [comment]
thinking about it again, network-based things might be poor indicator? Maybe we should do something else... Copy the sg/sg repo twice? :D @LawnGnome do you have ideas how to hack high io with not just sequential writing?

**Comment by BolajiOlajide** [comment]
Got any recommendation (asides running `yarn` in a repo)?

**Comment by eseliger** [comment]
I think cloning a reasonably large repo, like sg/sg, and then as the step command duplicating that repo 2 or 3 times should be ok? Not really sure, maybe there's some optimization that detects copies and does them in a rather quick, atomic operation?

**Comment by BolajiOlajide** [comment]
## Batch Spec

```yaml
name: 1-bind-investigation
description: Add Hello World to READMEs

# Find the first 100 search results for README files.
# This could yield less than 100 repos/workspaces if some repos contain multiple READMEs.
on:
  - repositoriesMatchingQuery: repo:^github.com\/sourcegraph\/ file:package.json count:2

# In each repository, run this command. Each repository's resulting diff is captured.
steps:
  - run: |
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && 
      yarn remove elm &&
      rm -rf pretter.config.js &&
      yarn &&
      yarn global add prettier &&
      echo "node_modules\n*.yaml\n*.json" >> .prettierignore &&
      prettier --config /tmp/.prettierrc --write .
    container: node:16.16.0
    files:
      /tmp/.prettierrc: |
        {
            "trailingComma": "es5",
            "tabWidth": 4,
            "semi": false,
            "singleQuote": true
        }

# Describe the changeset (e.g., GitHub pull request) you want for each repository.
changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: hello-world # Push the commit to this branch.
  commit:
    message: Append Hello World to all README.md files

```

### Summary

When dealing with heavy computations (especially one with IO operations/network calls), the `-workspace volume` option is significantly faster. The benchmark below was gotten with 10 runs to each command.

```txt
2882 files changed, 117792 insertions, 54217 deletions
  Execution took 22m16.562s
```

```txt
'src batch preview -v -workspace volume -clear-cache -f batch2.yaml' ran
    3.57 times faster than 'src batch preview -v -workspace bind -clear-cache -f batch2.yaml'
```

## Benchmark Result

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `src batch preview -v -workspace bind -clear-cache -f batch2.yaml` | 1351.901 | 1351.901 | 1351.901 | 3.57 |
| `src batch preview -v -workspace volume -clear-cache -f batch2.yaml` | 378.731 | 378.731 | 378.731 | 1.00 |

@eseliger Re-ran the bench with a more expensive operation making use of IO operations and network calls.
