### ISSUE TITLE
Workspaces: search_result_paths should only be within workspace

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#36620]
When using workspaces, I don't want to touch files outside of the workspace, hence the `onlyFetchWorkspace`. While doing some testing, I noticed that the script below would fail with file not found errors. That is because the `search_result_paths` property is never altered. It always contains ALL the matches for the repo, not considering the workspace.
Since this property is completely useless that way, I propose we change it to only contain the result paths that are relevant for this workspace. This is technically a breaking change but I doubt anyone relied on this, given it's useless 😬 

```yaml
on:
  - repositoriesMatchingQuery: file:README.md r:github.com/sourcegraph/sourcegraph

workspaces:
  - rootAtLocationOf: README.md
    onlyFetchWorkspace: true
    in: github.com/sourcegraph/sourcegraph

steps:
  - run: |
      for result in ${{ repository.search_result_paths }};
      do
          echo "Hello World" | tee -a "$result"
      done
    container: ubuntu:18.04
```
