### ISSUE TITLE
Workspaces: should nested workspaces be eliminated?

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#36621]
When a workspace definition like

```
workspaces:
  - rootAtLocationOf: package.json
    onlyFetchWorkspace: true
    in: github.com/sourcegraph/sourcegraph
```

matches

```
client/branded
client/web
client/web/enterprise
```

What should the outcome be? 
- 3 workspaces?
- 2 workspaces `{client/branded, client/web}`
- Something entirely different?

I'm not sure, but I found this to be quite strange when I discovered it.
