### ISSUE TITLE
Research spike Arch-Z (k8s)

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#36839]
Implements a portion of [RFC 696: Reduced isolation deployments for executor](https://docs.google.com/document/d/16SVTBbuqAc2RizJBZgBRCfv5fsMVhR_a2QrIHnEh5T0).

Explore how to write adjustments to our Kubernetes configs so that we can loosely bundle privileged executors on Kubernetes deployments. Findings should be added to product documentation (on installing/configuring executors).

**Comment by efritz** [comment]
Current work in progress:

```yaml
version: '2.4'
services:
  executor:
    container_name: executor
    image: 'index.docker.io/sourcegraph/executor:insiders@sha256:3bf01de9bf6a62eb750586b67151c4c94b82f3a928f545f00ff799279506c463'
    cpus: 1
    mem_limit: '4g'
    environment:
      # Points to own instance
      # sync with `executors.frontendURL` in site settings
      - EXECUTOR_FRONTEND_URL=http://sourcegraph-frontend-0:3080
      - EXECUTOR_FRONTEND_PASSWORD=hunter2hunter2hunter2
      # Choose what work to process
      - EXECUTOR_QUEUE_NAME=codeintel
      # Documenting defaults
      - EXECUTOR_MAXIMUM_RUNTIME_PER_JOB=30m
      - EXECUTOR_MAXIMUM_NUM_JOBS=2
      - EXECUTOR_NUM_TOTAL_JOBS=200
      - EXECUTOR_MAX_ACTIVE_TIME=2h
      # Run as root
      - UID=1000
      - GID=1000
      - TMPDIR=/tmp/sourcegraph/executor-scratch
    volumes:
      - '/tmp/sourcegraph/executor-scratch:/tmp/sourcegraph/executor-scratch'
      - '/var/run/docker.sock:/var/run/docker.sock'
    user: root
    privileged: true
    networks:
      - sourcegraph
    restart: always
```

**Comment by efritz** [comment]
Current work in progress:

`executor.Deployment.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Runs krazy kode.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
  name: executor
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: executor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: executor
    spec:
      containers:
      - name: executor
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # sync with `executors.frontendURL` in site config
        - name: EXECUTOR_FRONTEND_URL
          value: 'http://sourcegraph-frontend-0:3080'
          # sync with `executors.accessToken` in site config
        - name: EXECUTOR_FRONTEND_PASSWORD
          value: 'hunter2hunter2hunter2'
          # Choose what work to process
        - name: EXECUTOR_QUEUE_NAME
          value: 'codeintel'
          # Documenting defaults
        - name: EXECUTOR_MAXIMUM_RUNTIME_PER_JOB
          value: '30m'
        - name: EXECUTOR_MAXIMUM_NUM_JOBS
          value: '2'
        - name: EXECUTOR_NUM_TOTAL_JOBS
          value: '200'
        - name: EXECUTOR_MAX_ACTIVE_TIME
          value: '2h'
        # Hit dind sidecar
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        command:
          - sh
          - -c
          - 'sleep 10 && executor'
        image: index.docker.io/sourcegraph/executor:insiders@sha256:4909f85ba9b2446cf7c901dc735f265493b50e90acaf4cc0d36bac11d8c0d1b4
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /healthz
            port: debug
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: debug
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 6060
          name: debug
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: 4G
        #   requests:
        #     cpu: 500m
        #     memory: 2G
        securityContext:
          privileged: true
      - name: dind
        image: docker:20.10.7-dind@sha256:b36fdccb118bfaa8d5026da5183a077b87bc790051fcd2c5686bfb8f7fa2563c
        command:
          - 'dockerd'
          - '--tls=false'
          - '--mtu=1200'
          - '--host=tcp://0.0.0.0:2375'
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: 4G
        #   requests:
        #     cpu: 500m
        #     memory: 2G
        ports:
          - containerPort: 2375
            protocol: TCP
        securityContext:
          privileged: true

```

`executor.service.yaml`:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "6060"
    sourcegraph.prometheus/scrape: "true"
  labels:
    app: executor
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
  name: executor
spec:
  ports:
  - name: debug
    port: 6060
    targetPort: debug
  selector:
    app: executor
  type: ClusterIP
```
