### ISSUE TITLE
Research spike Arch-Z (docker-compose)

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#36838]
Implements a portion of [RFC 696: Reduced isolation deployments for executor](https://docs.google.com/document/d/16SVTBbuqAc2RizJBZgBRCfv5fsMVhR_a2QrIHnEh5T0).

Explore how to write a `docker-compose.override.yaml` file with our current executor distribution so that we can loosely bundle privileged executors on compose deployments. Findings should be added to product documentation (on installing/configuring executors).

**Comment by efritz** [comment]
Current work in progress:

```yaml
version: '2.4'
services:
  executor:
    container_name: executor
    image: 'index.docker.io/sourcegraph/executor:insiders@sha256:3bf01de9bf6a62eb750586b67151c4c94b82f3a928f545f00ff799279506c463'
    cpus: 1
    mem_limit: '4g'
    environment:
      # Points to own instance
      # sync with `executors.frontendURL` in site settings
      - EXECUTOR_FRONTEND_URL=http://sourcegraph-frontend-0:3080
      - EXECUTOR_FRONTEND_PASSWORD=hunter2hunter2hunter2
      # Choose what work to process
      - EXECUTOR_QUEUE_NAME=codeintel
      # Documenting defaults
      - EXECUTOR_MAXIMUM_RUNTIME_PER_JOB=30m
      - EXECUTOR_MAXIMUM_NUM_JOBS=2
      - EXECUTOR_NUM_TOTAL_JOBS=200
      - EXECUTOR_MAX_ACTIVE_TIME=2h
      # Run as root
      - UID=1000
      - GID=1000
      - TMPDIR=/tmp/sourcegraph/executor-scratch
    volumes:
      - '/tmp/sourcegraph/executor-scratch:/tmp/sourcegraph/executor-scratch'
      - '/var/run/docker.sock:/var/run/docker.sock'
    user: root
    privileged: true
    networks:
      - sourcegraph
    restart: always
```
