### ISSUE TITLE
migrator drift - error: unexpected status 404 from github

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#36973]
- **Sourcegraph version:** v3.40.1
- **Platform information:** 

#### Steps to reproduce:
Try out the new manual migrator command with the `drift` arg in a version besides `v3.40.1`

For example using the following `migrator.Job.yaml` running against an instance in `v3.40.1`
```yaml
# This manifest is provided in the event that someone may wish to execute
# database migrations outside of a code deployment.
#
# For more information, please see: https://docs.sourcegraph.com/admin/install/kubernetes/operations#database-migrations

---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
    description: Database migrator for Postgres databases
  labels:
    app.component.kubernetes/component: migrator
    deploy: sourcegraph
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: "index.docker.io/sourcegraph/migrator:insiders"
        args: ["drift", "--db=frontend", "--version=v3.39.1"]
        env:
          - name: PGHOST
            value: "pgsql"
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            value: "sg"
          - name: PGPASSWORD
            value: "sg"
          - name: PGDATABASE
            value: "sg"
          - name: PGSSLMODE
            value: "disable"
          - name: CODEINTEL_PGHOST
            value: "codeintel-db"
          - name: CODEINTEL_PGPORT
            value: "5432"
          - name: CODEINTEL_PGUSER
            value: "sg"
          - name: CODEINTEL_PGPASSWORD
            value: "sg"
          - name: CODEINTEL_PGDATABASE
            value: "sg"
          - name: CODEINTEL_PGSSLMODE
            value: "disable"
          - name: CODEINSIGHTS_PGHOST
            value: "codeinsights-db"
          - name: CODEINSIGHTS_PGPORT
            value: "5432"
          - name: CODEINSIGHTS_PGUSER
            value: "postgres"
          - name: CODEINSIGHTS_PGPASSWORD
            value: "password"
          - name: CODEINSIGHTS_PGDATABASE
            value: "postgres"
          - name: CODEINSIGHTS_PGSSLMODE
            value: "disable"
        resources:
          limits:
            cpu: 500m
            memory: 100M
          requests:
            cpu: 100m
            memory: 50M
      restartPolicy: OnFailure
  backoffLimit: 4
```

Run with the following command sequence
```
kubectl delete -f configure/migrator/migrator.Job.yaml --ignore-not-found=true
kubectl apply -f configure/migrator/migrator.Job.yaml
kubectl logs job.batch/migrator
```

#### Expected behavior:

This should show that the schema is out of sync

#### Actual behavior:
```
warrengifford@Warrens-MacBook-Pro deploy-sourcegraph-cse-k8s % kns logs job.batch/migrator
❗️ An error was returned when detecting the terminal size and capabilities:

   GetWinsize: inappropriate ioctl for device

   Execution will continue, but please report this, along with your operating
   system, terminal, and any other details, to:
     https://github.com/sourcegraph/sourcegraph/issues/new

error: unexpected status 404 from github
```

#### Things to note

This is failing for tags under `v3.40.x` as well as their commit hashes, however it works for both version tags and commit hashes in `v3.40.x`, which is incidentally the most current version of Sourcegraph and also the version of the instance being tested against. 

This has been observed to fail testing with arg `v3.39.1` against a Sourcegraph running in `v3.39.1` as well. 

A bad string passed in the arg for `v3.40x` is observed to error as expected
```

warrengifford@Warrens-MacBook-Pro deploy-sourcegraph-cse-k8s % kns logs job.batch/migrator
❗️ An error was returned when detecting the terminal size and capabilities:

   GetWinsize: inappropriate ioctl for device

   Execution will continue, but please report this, along with your operating
   system, terminal, and any other details, to:
     https://github.com/sourcegraph/sourcegraph/issues/new

error: failed to parse "v3.40.farts" - expected a version of the form `vX.Y.Z` or a 40-character commit hash
```

and fails in the same way for older versions

```
warrengifford@Warrens-MacBook-Pro deploy-sourcegraph-cse-k8s % kns logs job.batch/migrator
❗️ An error was returned when detecting the terminal size and capabilities:

   GetWinsize: inappropriate ioctl for device

   Execution will continue, but please report this, along with your operating
   system, terminal, and any other details, to:
     https://github.com/sourcegraph/sourcegraph/issues/new

error: failed to parse "v3.39.doom" - expected a version of the form `vX.Y.Z` or a 40-character commit hash
```

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).
