### ISSUE TITLE
batches: allow `repositoriesMatchingQuery` to specify the target branch

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#39186]
In #25228, we allowed users to provide multiple target branches in the same repository, but only when using the `repository` syntax; eg:

```yaml
on:
  - repository: github.com/sourcegraph/sourcegraph
    branches:
      - a
      - b
```

As noted in that ticket, we don't have equivalent functionality right now for users who are querying in general using `repositoriesMatchingQuery`. The search language _does_ support this with the `rev:` operator, but Batch Changes always uses the default branch for the matched repo at present, even if `rev:` is provided.

Whether we would want to support this via `rev:`, providing the same `branches` element on `repositoryMatchingQuery` objects, a combination, or something else entirely is TBD.
