### ISSUE TITLE
RFC 697 Multiple version upgrades: Testing - Code insights user story

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#40700]
See [RFC 697: Multiple version upgrades](https://docs.google.com/document/d/1eNiwzWZmfpvzFhs9IDcM7Sbchv_Hm8Uj-6bI-3TDlvg).

See the [testing strategy announcement in slack](https://sourcegraph.slack.com/archives/C02KZ941RNX/p1660748283465879).

This PR tracks general testing of multi-version upgrades as well as Code insights-specific test scenarios. 

**Core story (altered for code insights specifics)**:

Prior to upgrading, add dashboards/series configuration to site/org/user settings.

1. Run a search for the `sourcegraph/sourcegraph` repository
2. Search for the term `GetUploads` on `HEAD`
3. Open a result and ensure the file renders
4. Check that file sidebar and symbols sidebars are populated
5. Ensure code navigation (go to definition and find references) work as expected
6. Repeat steps 2-5 on an old tag to ensure that unindexed paths are also functional
7. Visit each site-admin page to ensure there are no obvious error banners
8. **Code insights migration test**: Ensure that the dashboards/series configured via site config are still available
9. **Code insights feature test**: Create a new insight and ensure the feature works properly at the new version

**Instructions**:

1. Start a local instance of Sourcegraph at version 3.34.0. The `docker-compose.yaml` artifact, below, provides an easy way to link a `sourcegraph/server` image with three container-based Postgres instances. The frontend, codeintel, and codeinsights databases are available on the host via ports 7777, 7778, and 7779, respectively.
2. Perform whatever steps listed above that need to be performed prior to upgrading (available on the host via port 7080).
3. Stop the `sourcegraph/server` container, but leave the three database containers running.
4. In a clone of the `sg/sg` repo, run the following commands to upgrade your local instance to version 4.0.

```bash
export PGDATASOURCE=postgres://sg:sg@127.0.0.1:7777/sg
export CODEINTEL_PGDATASOURCE=postgres://sg:sg@127.0.0.1:7778/sg
export CODEINSIGHTS_PGDATASOURCE=postgres://sg:sg@127.0.0.1:7779/sg

go run ./enterprise/cmd/migrator upgrade --from 3.34 --to 4.0
```

5. Update the tag on the `sourcegraph/server` image to point to the "pre-release" of version 4.0. The particular commit that we're treating as the 4.0 release prior to the creation of the tag in git can be found [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/migration/stitch/git.go?L128=).

_For code insights_, it may be necessary to replace the `pgsql-codeinsights` image with `sourcegraph/postgres-12-alpine` when booting the new version (using the same volume mount).

**Artifacts**:

`docker-compose.yaml`:

```yaml
version: '2.4'
services:
  sourcegraph:
    image: sourcegraph/server:{{TAG GOES HERE}}
    environment:
      - PGDATASOURCE=postgres://sg:sg@pgsql-frontend:5432/sg
      - CODEINTEL_PGDATASOURCE=postgres://sg:sg@pgsql-codeintel:5432/sg
      - CODEINSIGHTS_PGDATASOURCE=postgres://sg:sg@pgsql-codeinsights:5432/sg
    ports:
      - 7080:7080
    networks:
      - sourcegraph
    depends_on:
      - pgsql-frontend
      - pgsql-codeintel
      - pgsql-codeinsights

  pgsql-frontend:
    image: sourcegraph/postgres-12-alpine
    volumes:
      - 'pgsql-frontend:/data'
    ports:
      - 7777:5432
    networks:
      - sourcegraph

  pgsql-codeintel:
    image: sourcegraph/postgres-12-alpine
    volumes:
      - 'pgsql-codeintel:/data'
    ports:
      - 7778:5432
    networks:
      - sourcegraph

  pgsql-codeinsights:
    image: sourcegraph/codeinsights-db
    volumes:
      - 'pgsql-codeinsights:/data'
    ports:
      - 7779:5432
    networks:
      - sourcegraph

volumes:
  sourcegraph:
  pgsql-frontend:
  pgsql-codeintel:
  pgsql-codeinsights:

networks:
  sourcegraph:
```

**Comment by Joelkw** [comment]
Update: this is blocked until @efritz adds explicitly unblocks: 

Each of these issues are currently blocked by my own progress. Before others test, I need to add a few shims to allow pre-testing of the 4.0 release before the tag is made in Git.
I’ll be adding explicit instructions to these issues and tagging back in this thread once they’re ready to be tackled (starting in the next day or so).

**Comment by efritz** [comment]
@Joelkw Added instructions - this issue should be good to perform whenever :)

**Comment by efritz** [comment]
On second thought, out of band migrations for codeinsights may not work properly until #40753. I believe @coury-clark is out the rest of the week so I have a few days to patch this still.

**Comment by efritz** [comment]
@Joelkw @felixfbecker Unblocked! I do not believe that #40753 was actually a problem. I just made up an impossible condition I thought we needed to be cautious of.

**Comment by coury-clark** [comment]
Test scenario:

- User custom dashboard with user, org, global insight




![Image](https://user-images.githubusercontent.com/5090588/187293200-d4004b8b-f0da-4b2a-92a7-180b772bf235.png)


- Org custom dashboard with org, global insight



![Image](https://user-images.githubusercontent.com/5090588/187293234-6cd702c6-b276-4ed9-8361-e621e4aa41a1.png)
- Global dashboard with global insight

![Image](https://user-images.githubusercontent.com/5090588/187293372-22db0d68-0e3c-4795-b7d8-946f0d32cceb.png)

- User specific dashboard


![Image](https://user-images.githubusercontent.com/5090588/187293472-b83cc6c7-a5a3-4b36-97c2-c0a859422ac2.png)


- Org specific dashboard



![Image](https://user-images.githubusercontent.com/5090588/187293518-aef3ece2-0da7-49e9-9a4b-d663b84e636a.png)

**Comment by coury-clark** [comment]
Since we have restrictions in the `server` image from starting the Code Insights backend at 3.34, and different but similar problems in 4.0 I had to validate the data in the db explicitly. Here are some tables pulled after migrating the scenario above (different names, I had to recreate the data) from 3.34 to 4.0.

```markdown
postgres=# select * from insight_view;
 id | title  | description |             unique_id              | default_filter_include_repo_regex | default_filter_exclude_repo_regex | other_threshold | presentation_type | is_frozen | default_filter_search_contexts | series_sort_mode | series_sort_direction | series_limit 
----+--------+-------------+------------------------------------+-----------------------------------+-----------------------------------+-----------------+-------------------+-----------+--------------------------------+------------------+-----------------------+--------------
  1 | global |             | searchInsights.insight.global      |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
  2 | org    |             | searchInsights.insight.org-org-1   |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
  3 | user   |             | searchInsights.insight.user-user-1 |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
(3 rows)
```

```markdown
postgres=# select * from dashboard;
 id |        title         |         created_at         | created_by_user_id |      last_updated_at       | deleted_at | save |   type   
----+----------------------+----------------------------+--------------------+----------------------------+------------+------+----------
  1 | global custom        | 2022-08-30 22:29:20.409829 |                    | 2022-08-30 22:29:20.409829 |            | t    | standard
  2 | Global Insights      | 2022-08-30 22:29:20.428385 |                    | 2022-08-30 22:29:20.428385 |            | t    | standard
  3 | northpole org custom | 2022-08-30 22:29:20.475139 |                    | 2022-08-30 22:29:20.475139 |            | t    | standard
  4 | northpole's Insights | 2022-08-30 22:29:20.490967 |                    | 2022-08-30 22:29:20.490967 |            | t    | standard
  5 | asdf                 | 2022-08-30 22:29:20.543587 |                    | 2022-08-30 22:29:20.543587 |            | t    | standard
  6 | user private custom  | 2022-08-30 22:29:20.552949 |                    | 2022-08-30 22:29:20.552949 |            | t    | standard
  7 | test's Insights      | 2022-08-30 22:29:20.569023 |                    | 2022-08-30 22:29:20.569023 |            | t    | standard
(7 rows)
```

```markdown
postgres=# select * from insight_view_grants ivg join insight_view iv on iv.id = ivg.insight_view_id;
 id | insight_view_id | user_id | org_id | global | id | title  | description |             unique_id              | default_filter_include_repo_regex | default_filter_exclude_repo_regex | other_threshold | presentation_type | is_frozen | default_filter_search_contexts | series_sort_mode | series_sort_direction | series_limit 
----+-----------------+---------+--------+--------+----+--------+-------------+------------------------------------+-----------------------------------+-----------------------------------+-----------------+-------------------+-----------+--------------------------------+------------------+-----------------------+--------------
  1 |               1 |         |        | t      |  1 | global |             | searchInsights.insight.global      |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
  2 |               2 |         |      1 |        |  2 | org    |             | searchInsights.insight.org-org-1   |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
  3 |               3 |       1 |        |        |  3 | user   |             | searchInsights.insight.user-user-1 |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
(3 rows)
```

```markdown
postgres=# select * from dashboard_grants dg join dashboard db on db.id = dg.dashboard_id;
 id | dashboard_id | user_id | org_id | global | id |        title         |         created_at         | created_by_user_id |      last_updated_at       | deleted_at | save |   type   
----+--------------+---------+--------+--------+----+----------------------+----------------------------+--------------------+----------------------------+------------+------+----------
  1 |            1 |         |        | t      |  1 | global custom        | 2022-08-30 22:29:20.409829 |                    | 2022-08-30 22:29:20.409829 |            | t    | standard
  2 |            2 |         |        | t      |  2 | Global Insights      | 2022-08-30 22:29:20.428385 |                    | 2022-08-30 22:29:20.428385 |            | t    | standard
  3 |            3 |         |      1 |        |  3 | northpole org custom | 2022-08-30 22:29:20.475139 |                    | 2022-08-30 22:29:20.475139 |            | t    | standard
  4 |            4 |         |      1 |        |  4 | northpole's Insights | 2022-08-30 22:29:20.490967 |                    | 2022-08-30 22:29:20.490967 |            | t    | standard
  5 |            5 |       1 |        |        |  5 | asdf                 | 2022-08-30 22:29:20.543587 |                    | 2022-08-30 22:29:20.543587 |            | t    | standard
  6 |            6 |       1 |        |        |  6 | user private custom  | 2022-08-30 22:29:20.552949 |                    | 2022-08-30 22:29:20.552949 |            | t    | standard
  7 |            7 |       1 |        |        |  7 | test's Insights      | 2022-08-30 22:29:20.569023 |                    | 2022-08-30 22:29:20.569023 |            | t    | standard
(7 rows)
```

```markdown
postgres=# select * from insight_series i join insight_view_series ivs on ivs.insight_series_id = i.id join insight_view iv on iv.id = ivs.insight_view_id;;
 id |          series_id          | query  |         created_at         |    oldest_historical_at    |  last_recorded_at   |    next_recording_after    | deleted_at | backfill_queued_at |  last_snapshot_at   | next_snapshot_after |             repositories             | sample_interval_unit | sample_interval_value | generated_from_capture_groups | generation_method | just_in_time | group_by | backfill_attempts | needs_migration | insight_view_id | insight_series_id | label  |      stroke       | id | title  | description |             unique_id              | default_filter_include_repo_regex | default_filter_exclude_repo_regex | other_threshold | presentation_type | is_frozen | default_filter_search_contexts | series_sort_mode | series_sort_direction | series_limit 
----+-----------------------------+--------+----------------------------+----------------------------+---------------------+----------------------------+------------+--------------------+---------------------+---------------------+--------------------------------------+----------------------+-----------------------+-------------------------------+-------------------+--------------+----------+-------------------+-----------------+-----------------+-------------------+--------+-------------------+----+--------+-------------+------------------------------------+-----------------------------------+-----------------------------------+-----------------+-------------------+-----------+--------------------------------+------------------+-----------------------+--------------
  1 | 2E5w4LGovSxmHH9ZJPqI8eNXDLT | global | 2022-08-30 22:29:20.38198  | 2022-03-01 22:29:20.38198  | 0001-01-01 00:00:00 | 2022-10-30 22:29:20.38198  |            |                    | 0001-01-01 00:00:00 | 2022-08-31 00:00:00 | {github.com/sourcegraph/sourcegraph} | MONTH                |                     2 | f                             | SEARCH            | t            |          |                 0 | f               |               1 |                 1 | global | var(--oc-grape-7) |  1 | global |             | searchInsights.insight.global      |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
  2 | 2E5w4MlyCyjoyDjlEipbkzfyvdV | org    | 2022-08-30 22:29:20.458258 | 2022-03-01 22:29:20.458258 | 0001-01-01 00:00:00 | 2022-10-30 22:29:20.458258 |            |                    | 0001-01-01 00:00:00 | 2022-08-31 00:00:00 | {github.com/sourcegraph/sourcegraph} | MONTH                |                     2 | f                             | SEARCH            | t            |          |                 0 | f               |               2 |                 2 | org    | var(--oc-grape-7) |  2 | org    |             | searchInsights.insight.org-org-1   |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
  3 | 2E5w4Kn4LoD3sD1oL1VL2fQISuz | user   | 2022-08-30 22:29:20.516912 | 2022-03-01 22:29:20.516912 | 0001-01-01 00:00:00 | 2022-10-30 22:29:20.516912 |            |                    | 0001-01-01 00:00:00 | 2022-08-31 00:00:00 | {github.com/sourcegraph/sourcegraph} | MONTH                |                     2 | f                             | SEARCH            | t            |          |                 0 | f               |               3 |                 3 | user   | var(--oc-grape-7) |  3 | user   |             | searchInsights.insight.user-user-1 |                                   |                                   |                 | LINE              | f         |                                |                  |                       |             
(3 rows)
```

```markdown
postgres=# select db.*, array_agg(iv.title) as insight_view_titles from dashboard db join dashboard_insight_view div on div.dashboard_id = db.id join insight_view iv on iv.id = div.insig
ht_view_id group by db.id;
 id |        title         |         created_at         | created_by_user_id |      last_updated_at       | deleted_at | save |   type   |     insight_view_titles     
----+----------------------+----------------------------+--------------------+----------------------------+------------+------+----------+-------------------
  1 | global custom        | 2022-08-30 22:29:20.409829 |                    | 2022-08-30 22:29:20.409829 |            | t    | standard | {global}
  2 | Global Insights      | 2022-08-30 22:29:20.428385 |                    | 2022-08-30 22:29:20.428385 |            | t    | standard | {global}
  3 | northpole org custom | 2022-08-30 22:29:20.475139 |                    | 2022-08-30 22:29:20.475139 |            | t    | standard | {global,org}
  4 | northpole's Insights | 2022-08-30 22:29:20.490967 |                    | 2022-08-30 22:29:20.490967 |            | t    | standard | {org}
  6 | user private custom  | 2022-08-30 22:29:20.552949 |                    | 2022-08-30 22:29:20.552949 |            | t    | standard | {user,org,global}
  7 | test's Insights      | 2022-08-30 22:29:20.569023 |                    | 2022-08-30 22:29:20.569023 |            | t    | standard | {user}
(6 rows)
```

**Comment by coury-clark** [comment]
Just leaving notes on what I did to get it running

``` yaml
version: '2.4'
services:
  sourcegraph:
    image: sourcegraph/server:3.34.0
    environment:
      - PGDATASOURCE=postgres://sg:sg@pgsql-frontend:5432/sg
      - CODEINTEL_PGDATASOURCE=postgres://sg:sg@pgsql-codeintel:5432/sg
      - CODEINSIGHTS_PGDATASOURCE=postgres://postgres:password@pgsql-codeinsights:5432/postgres
      - ALLOW_SINGLE_DOCKER_CODE_INSIGHTS=true
    ports:
      - 7080:7080
    networks:
      - sourcegraph
    depends_on:
      - pgsql-frontend
      - pgsql-codeintel
      - pgsql-codeinsights

  pgsql-frontend:
    image: sourcegraph/postgres-12-alpine
    volumes:
      - 'pgsql-frontend:/data'
    ports:
      - 7777:5432
    networks:
      - sourcegraph

  pgsql-codeintel:
    image: sourcegraph/postgres-12-alpine
    volumes:
      - 'pgsql-codeintel:/data'
    ports:
      - 7778:5432
    networks:
      - sourcegraph

  pgsql-codeinsights:
    image: sourcegraph/codeinsights-db:3.34.0
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - 'pgsql-codeinsights:/data'
    ports:
      - 7779:5432
    networks:
      - sourcegraph

volumes:
  sourcegraph:
  pgsql-frontend:
  pgsql-codeintel:
  pgsql-codeinsights:

networks:
  sourcegraph:

```
