### ISSUE TITLE
precise-code-intel-worker doesn't respect manage bucket environment variable

### ISSUE THREAD

**Issue by rdeusser** [sourcegraph/sourcegraph#41597]
- **Sourcegraph version:** v3.42.2
- **Platform information:** Kubernetes v1.20.1

#### Steps to reproduce:

1. Deploy Sourcegraph helm chart to a Kubernetes cluster setup to use an external Minio cluster with the following environment variables set:
```yaml
- name: PRECISE_CODE_INTEL_UPLOAD_BACKEND
  value: "minio"
- name: PRECISE_CODE_INTEL_UPLOAD_BUCKET
  value: "<existing bucket name>"
- name: PRECISE_CODE_INTEL_UPLOAD_MANAGE_BUCKET
  value: "false"
- name: PRECISE_CODE_INTEL_UPLOAD_AWS_ENDPOINT
  value: "https://<minio-cluster-url>"
- name: PRECISE_CODE_INTEL_UPLOAD_AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      key: user
      name: minio
- name: PRECISE_CODE_INTEL_UPLOAD_AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      key: password
      name: minio
```
2. Upload LSIF data to deployed Sourcegraph instance.
3. `precise-code-intel-worker` after a few minutes will fail with a FATAL log:
```json
{
  "SeverityText": "FATAL",
  "Timestamp": 1662751146795123700,
  "InstrumentationScope": "worker",
  "Caller": "precise-code-intel-worker/main.go:112",
  "Function": "main.main",
  "Body": "Failed to initialize uploadstore",
  "Resource": {
    "service.name": "precise-code-intel-worker",
    "service.version": "3.42.2",
    "service.instance.id": "precise-code-intel-worker-5d9b575245-vhwh6"
  },
  "Attributes": {
    "error": "failed to create bucket: operation error S3: CreateBucket, retry quota exceeded, 0 available, 5 requested"
  }
}
```

#### Expected behavior:
`failed to create bucket` is an error that seems to occur in two places:

1. The GCS client
2. The S3 client

I would expect that the environment variable `PRECISE_CODE_INTEL_UPLOAD_MANAGE_BUCKET` being set to `false` would cause this method:
```go
func (s *s3Store) Init(ctx context.Context) error {
	if !s.manageBucket {
		return nil // <------ with manageBucket false it should return here
	}

	if err := s.create(ctx); err != nil {
		return errors.Wrap(err, "failed to create bucket")
	}

	if err := s.update(ctx); err != nil {
		return errors.Wrap(err, "failed to update bucket attributes")
	}

	return nil
}
```
to return before the creation of the bucket.

#### Actual behavior:
The S3 client tries to create the bucket despite `PRECISE_CODE_INTEL_UPLOAD_MANAGE_BUCKET` being set to `false`.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).
