### ISSUE TITLE
Long Running Executions go back to queued icon

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#44856]
While working on large diffs for scaletesting (#44503), a workspace correctly goes from queued to processing (showing the spinner). However, after a while the workspace icon goes back to queued.

Selecting the workspace shows the **Step** is actually being processed (has the spinner), and in **Diagnostics** you can see the logs coming through.

Note: Could be related to the executor being shown as not up

## Screenshots
![Screenshot 2022-11-28 at 10 50 32](https://user-images.githubusercontent.com/38407415/204362295-2e1692fa-57f4-4b21-9f3f-0b81ba1bd866.png)

<img width="1110" alt="Screenshot 2022-11-28 at 11 00 15" src="https://user-images.githubusercontent.com/38407415/204362423-0c69d217-559a-4e62-b39f-e507599e6332.png">

![Screenshot 2022-11-28 at 12 14 38](https://user-images.githubusercontent.com/38407415/204362477-0d8adcca-ab1e-40ab-b742-484ec85cd1d1.png)

![Screenshot 2022-11-28 at 12 17 23](https://user-images.githubusercontent.com/38407415/204362496-9de00ec9-5e32-495d-ab11-46c34060b21b.png)

## Example Spec

```yaml
name: large-diffs
description: Add Hello World to READMEs

on:
  - repository: ghe.sgdev.org/scaletesting/large-binary-files

steps:
  - run: find . -type f -not -path '*/\.git/*' -exec sed -i 's/x/z/g' {} \;
    container: alpine:3

changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: hello-world # Push the commit to this branch.
  commit:
    message: Append Hello World to all README.md files
```
