### ISSUE TITLE
scaletesting: Efficiently apply large changesets

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#45583]
Result of #44678.

When applying a large number of changesets (125k), the requests times out after a certain time (~1min).

The bottleneck is [updating each changesets one-by-one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/batches/service/service_apply_batch_change.go?L160-168).

This process exceeds 15minutes when running locally.

The entire changeset is being updated because the `Rewire` function is update a number of fields (beyond the ui publication state).

Apply changesets needs to happen more efficiently (either DB operation or async) to unblock the applying of a large number of changesets.

## Ideas

* Determine a SQL Query (or queries) to more efficiently update a large quantity of changesets
* Begin the process of applying the changesets asynchronously
    * Much like how we determine the workspaces when performing server-side, run the process async and ask for process state every so often. If complete, advance to the next stage.

## Done

Be able to apply 125k changesets

## Spec

```yaml
name: GHE-125k
description: Add Hello World to READMEs

on:
  - repositoriesMatchingQuery: repo:^ghe-scaletesting.sgdev.org/main-org.*$ count:125000

steps:
  - run: IFS=$'\n'; echo Hello World | tee -a $(find -name README.md)
    container: ubuntu:18.04

changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: hello-world # Push the commit to this branch.
  commit:
    message: Append Hello World to all README.md files
```

## Local Dev Help

I (@Piszmog) have a python script that allows you to setup a preview of 125k changesets in about 2-2.5 hours locally (avoids docker, so no worries with docker+mac issues)
