### ISSUE TITLE
zoekt webserver failing with "cannot allocate memory"

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#45692]
Occurring on `v4.3.0-rc.3` on our `rctest` instance.

[Log.txt](https://github.com/sourcegraph/sourcegraph/files/10233949/Untitled.txt)

Link to Google Cloud Logging: https://cloudlogging.app.goo.gl/7vo6bnbZ8eSLfWso9

This is a release-blocking issue for the 4.3 release. 

Relevant lines from the panic above:

```
2022/12/15 05:13:59 reloading: /data/index/github.com%2Fwp-plugins%2Fbuddypress-custom-profile-filters_v16.00000.zoekt, err cannot allocate memory
2022/12/15 05:13:59 reloading: /data/index/github.com%2Fwp-plugins%2Fbuddypress-custom-profile-menu_v16.00000.zoekt, err cannot allocate memory
fatal error: runtime: out of memory
2022/12/15 05:13:59 reloading: /data/index/github.com%2Fwp-plugins%2Fbuddypress-dataminer_v16.00000.zoekt, err cannot allocate memory

runtime stack:
runtime.throw({0x10a5285?, 0x2030?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc00030de00 sp=0xc00030ddd0 pc=0x43a0bd
runtime.sysMapOS(0xc169800000, 0x400000?)
	/usr/local/go/src/runtime/mem_linux.go:187 +0x11b fp=0xc00030de48 sp=0xc00030de00 pc=0x418bfb
runtime.sysMap(0xc3ffffffff?, 0x7fadc4a5d000?, 0x42df40?)
	/usr/local/go/src/runtime/mem.go:142 +0x35 fp=0xc00030de78 sp=0xc00030de48 pc=0x4185d5
runtime.(*mheap).grow(0x1ff2440, 0x39?)
	/usr/local/go/src/runtime/mheap.go:1459 +0x23d fp=0xc00030dee8 sp=0xc00030de78 pc=0x42af3d
runtime.(*mheap).allocSpan(0x1ff2440, 0x39, 0x0, 0x1)
	/usr/local/go/src/runtime/mheap.go:1191 +0x1be fp=0xc00030df80 sp=0xc00030dee8 pc=0x42a69e
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:910 +0x65 fp=0xc00030dfc8 sp=0xc00030df80 pc=0x42a125
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:492 +0x49 fp=0xc00030dfd0 sp=0xc00030dfc8 pc=0x46c109
```

This instance can be requested through Slack with Entitle (`/access_request` in Slack). 

After access is granted, you should run `make install` to build the latest version of the `mi` tool. 
Then you can run `mi ssh` within the `rctest` folder to access the instance.

**Comment by daxmc99** [comment]
We have also enabled Google SSO login on the instance to allow for easier debugging.

Result: Indexed search results are not available on the system

**Comment by keegancsmith** [comment]
This happens when there isn't enough ram usually. We haven't changed anything in zoekt that should change memory usage. @daxmc99  Is it possible the instance is just under provisioned? cc @sourcegraph/search-core

**Comment by daxmc99** [comment]
This is the same instance configuration we had before. 
I can increase the ram on the instance though

**Comment by daxmc99** [comment]
![CleanShot 2022-12-14 at 23 28 53](https://user-images.githubusercontent.com/31839142/207788693-4be1d21d-af65-4b54-85bd-e2a5a9e86410.png)

After restarting the zoekt-webserver we no longer see the behavior.

**Comment by daxmc99** [comment]
I'm removing the release blocker label. This is strange behavior but not something that endangers the release. 

It appears that Zoekt went through a period of being unable to allocate enough memory but now is happily using only 5.78GiB of its allocation of 50 GB.

**Comment by daxmc99** [comment]
@sourcegraph/cloud 
From `docker inspect` it looks like this container has been restarted `102` times. 
This seems like a significant gap in our monitoring

**Comment by daxmc99** [comment]
Confirmed this is only occurring on the `rctest` instance

**Comment by rafax** [comment]
`sudo sysctl -w vm.max_map_count=300000` fixed this - was `rctest` rebuilt recently/

**Comment by daxmc99** [comment]
Also related: https://github.com/sourcegraph/sourcegraph/pull/46123
We saw the "Zoekt not all replicas available message on the instance" which prompted the investigation where we found the logs

**Comment by daxmc99** [comment]
Also seeing this on `indexed-search` when deploying to Kubernetes.

**Comment by daxmc99** [comment]
![CleanShot 2023-02-20 at 13 36 35](https://user-images.githubusercontent.com/31839142/220109874-68c7bf61-0e1e-41f7-a6c0-ba8fd118f9f6.png)

**Comment by daxmc99** [comment]
Ultimately solved by applying a `DaemonSet` to the cluster

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: sysctl-conf
  name: sysctl-conf
spec:
  selector:
    matchLabels:
      k8s-app: sysctl-conf
  template:
    metadata:
      labels:
        k8s-app: sysctl-conf
    spec:
      containers:
      - command:
        - sh
        - -c
        - sysctl -w vm.max_map_count=262166 && while true; do sleep 86400; done
        image: busybox:1.26.2
        name: sysctl-conf
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 1
```
