### ISSUE TITLE
[K8s Testing] - Test Executors on Air Gapped Env

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#50826]
# Testing Executors on Air Gapped env

Ensure Executors for Kubernetes works in an Air Gapped environment. We will use this to simulate a customer deployment.

Goal: Working Executors with no unauthorized ingress/egress traffic

```[tasklist]
## Create Air Gapped environment in GCP
- [x] Create Cloud (GCP) project with a Kubernetes Cluster
- [x] Put Cluster in a VPC that has no inbound or outbound traffic without exceptions
- [x] Setup artifact registry within cluster
- [x] Deploy a colocated Code Host within the cluster
```
```[tasklist]
## Deploy Sourcegraph and test Executors
- [x] Deploy Sourcegraph and test executors on them
- [x] Sync repos and check network traffic
- [x] Check if there are any issues with network
- [x] Check Executor job spawns, CPU/Mem usage, Job completion & lifecycle
- [x] Monitor Cluster usage spikes, determine how jobs get throttled upon cluster resource limitations
- [x] Validate running without root user
```

### Batch Changes

Ensure Native SSBC is feature flag enabled.

1. Create a new Batch Change
2. Have 10+ repositories be selected by the batch spec
3. Run the batch change
4. Ensure the batch change is applied correctly to the workspace.

### Code Intel

1. Enable [Precise Code Nav](https://docs.sourcegraph.com/code_navigation/how-to/enable_auto_indexing).
2. run indexing across 10+ repositories.

**Comment by danieldides** [comment]
# Airgap Testing Setup

## Create Cloud (GCP) project with a Kubernetes Cluster
After trying to build it by hand for a little bit, it was quickly obvious that the easiest way to accomplish this is to start with a Sourcegraph Cloud instance and work backwards: https://github.com/sourcegraph/cloud/blob/main/environments/dev/deployments/src-c068a5e5eff197363116/dashboard.md

## Put Cluster in a VPC that has no inbound or outbound traffic without exceptions
Cloud instances by default obviously have ingress and egress traffic allowed. To disable this and create a more "airgapped" environment, we need to remove the Cloud NAT feature. Open the GCP project (you will need to request `Sourcegraph Cloud V2 Internal Access` on entitle ) and go to the [`Cloud NAT - Network Services`](https://console.cloud.google.com/net-services/nat/list?referrer=search&project=src-c54bde77ebd01257330e) interface. Here, we want to delete both the NAT gateway for the main cluster vpc as well as the executors VPC:

![delete-nat](https://user-images.githubusercontent.com/8784265/235475639-e1e98f6e-f5b6-4717-b4c4-322108bbb355.png)

Removing these will prevent any outbound traffic from the cluster, effectively blocking the cluster from pulling containers from Docker Hub. Note: this won't stop ingress traffic, so the frontend is still available.

We can confirm that the `kubelet` is unable to pull images by creating a test deployment with a recent container image:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sourcegraph-server
  labels:
    app: src-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sourcegraph-server
  template:
    metadata:
      labels:
        app: sourcegraph-server
    spec:
      containers:
      - name: sourcegraph-server
        image: sourcegraph/server:insiders@sha256:21dce9e63d4f928a77e71ee5903f51bc7d84745636b41ae674ba7f562b9fd472 
        ports:
        - containerPort: 80
```

Then apply this to the cluster with `kubectl -f test.yaml` and wait. The cluster should attempt to pull the image and eventually fail (5-10 minutes):
```
k get pods | grep sourcegraph-server
sourcegraph-server-649477b68-wszhx          0/1     ImagePullBackOff   0             9m7s
daniel@Daniels-MacBook-Pro ~/P/w/s/e/airgap-testing> 
```

## Setup Artifact Registry within the cluster
Using the Sourcegraph Cloud deployment method, we already have Artifact Registry [deployed](https://console.cloud.google.com/artifacts/docker/src-c54bde77ebd01257330e/us-central1/cloud-internal-images-mirror?project=src-c54bde77ebd01257330e) but it is not scoped correctly.

To grant access to Artifact Registry, add the following OAuth scopes to the `config.yaml` file in the Cloud repo:
```yaml
gcp:
  gke:
    blue:
      additionalOauthScopes:
      - https://www.googleapis.com/auth/devstorage.read_only
```

And reapply the CDKTF. This will restart the application. You will also need to grant the Service Account `Artifact Registry Reader`.

### Add containers to Artifact Registry

We can add additional containers we need to the registry with this simple script (thanks, Cody!):
```bash
#!/bin/bash

# List of container images to pull and push 
images=(
"cadvisor"
"frontend"
"github-proxy"
"gitserver"
"indexed-searcher"
"migrator"
"opentelemetry-collector"
"precise-code-intel-worker"
"prometheus-gcp"
"redis-store"
"redis_exporter"
"repo-updater"
"search-indexer"
"searcher"
"symbols"
"syntax-highlighter"
"worker"
"executor-kubernetes"
"lsif-go"
"batcheshelper"
)
tag="215272_2023-04-25_5.0-e2762cfbb4df"

# Docker Hub registry 
REGISTRY_TO_PULL="docker.io"  

# Alternative registry to push to 
REGISTRY_TO_PUSH="us-central1-docker.pkg.dev/src-c54bde77ebd01257330e/cloud-internal-images-mirror"

for image in "${images[@]}" 
do
  docker pull $REGISTRY_TO_PULL/sourcegraph/$image:$tag --platform=amd64
  
  # Tag the image for the target registry
  docker tag sourcegraph/$image:$tag $REGISTRY_TO_PUSH/sourcegraph/$image:$tag
  
  # Push the image to the alternative registry
  docker push $REGISTRY_TO_PUSH/sourcegraph/$image:$tag
done
```

## Deploy a colocated Code Host within the cluster
We're going to deploy Gogs within the cluster and add a few repositories to it so that we have code for the executors to work on.

### Deploying Gogs
Deploy the Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: gogs-app
  namespace: default
  labels:
    app: gogs-app
spec:
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30022
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30009
  selector:
    app: gogs-app
  type: NodePort
```

Upload the container image for the `StatefulSet`:

```bash
IMAGE_TO_PULL="gogs/gogs:latest"
REGISTRY_TO_PULL="docker.io"
REGISTRY_TO_PUSH="us-central1-docker.pkg.dev/src-c54bde77ebd01257330e/cloud-internal-images-mirror"
docker pull $REGISTRY_TO_PULL/$IMAGE_TO_PULL
docker tag $IMAGE_TO_PULL $REGISTRY_TO_PUSH/$IMAGE_TO_PULL
docker push $REGISTRY_TO_PUSH/$IMAGE_TO_PULL
```

Apply the `StatefulSet` manifest:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gogs-app
  name: gogs-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs-app
  serviceName: gogs-app
  template:
    metadata:
      labels:
        app: gogs-app
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/src-c54bde77ebd01257330e/cloud-internal-images-mirror/gogs/gogs
        imagePullPolicy: IfNotPresent
        name: gogs-app
        resources: {}
        ports:
          - containerPort: 3000
            name: web
            protocol: TCP
          - containerPort: 22
            name: ssh
            protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
```
### Add Code to Gogs
`kubectl port-forward -n default gogs-app-0 3000` and navigate to `localhost:3000` in your browser.Complete the onboarding steps to configure Gogs with `sqlite3`.

Once configured, we can start adding repositories. Identify a repo you'd like to push, "Create" an empty Repo on Gogs (using the `+` in the top right), and clone the repo locally from github. Navigate to the repo directory and add a new upstream with:
```
git remote add gogs http://localhost:3000/daniel/k9s.git
```
The push the checkout with `git push -u gogs <branch_name>`. It should show in Gogs. Repeat this for ~10 repositories.

# Deploy Sourcegraph and test executors
## Deploy sourcegraph and test executors on them
Sourcegraph is deployed by default with the Cloud instances. Depending on order of operations, it may be failing to pull images though. We'll want to update our Sourcegraph kubernetes manifests to pull from artifact registry. The easiest way to do that is to update the `config.yaml` to include:
```yaml
releaseChannel: insiders
sourcegraphVersion: 215272_2023-04-25_5.0-e2762cfbb4df
```

This will also set us to a later dev version of Sourcegraph with all the necessary changes required.

And regenerate the kustomize with `mi2 generate kustomize`. Once that's complete, hand modify the kustomization file in `kubernetes/sg/override.yaml` to include the repository override:
```
+sourcegraph:
+  image:
+    defaultTag: 215272_2023-04-25_5.0-e2762cfbb4df
+    repository: us-central1-docker.pkg.dev/src-c54bde77ebd01257330e/cloud-internal-images-mirror/sourcegraph
+    useGlobalTagAsDefault: true
```
If you execute a kustomize diff now, it should show all the containers being updated to the correct version pulled from artifact registry

## Deploy the executors
Checkout `sourcegraph/sourcegraph` at a recent version and navigate to `enterprise/cmd/executors/kubernetes` and follow the instructions for making a `Secret` value. Set that in the Site Config as `executors.accessToken` as well.

For the most part, the manifests included in https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+file%3A%5Eenterprise%2Fcmd%2Fexecutor%2Fkubernetes&patternType=standard&sm=1&groupBy=path are complete, but we will need to make some changes to all files to make them work for our deployment:

### Update the namespace
Cloud deploys into a unique namespace:
```
sed -i '' 's/namespace: default/namespace: src-ed654e65e35cf36daa38/g' *.yml
```

### Configure Batches Deployment and Create Code Intel resources
`executor-codeintel.Deployment.yaml`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-executor-codeintel
  namespace: src-ed654e65e35cf36daa38
spec:
  selector:
    matchLabels:
      app: sg-executor-codeintel
  template:
    metadata:
      namespace: src-ed654e65e35cf36daa38
      labels:
        app: sg-executor-codeintel
    spec:
      serviceAccountName: sg-executor-codeintel-service-account
      securityContext:
        runAsUser: 0
      containers:
        - name: sg-executor-codeintel
          image: us-central1-docker.pkg.dev/src-c54bde77ebd01257330e/cloud-internal-images-mirror/sourcegraph/executor-kubernetes:randell1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: EXECUTOR_FRONTEND_URL
              # For development purposes. We usually run Sourcegraph in Docker.
              value: http://sourcegraph-frontend:30080
            - name: EXECUTOR_FRONTEND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: executor-frontend-password
                  key: EXECUTOR_FRONTEND_PASSWORD
            - name: EXECUTOR_QUEUE_NAME
              value: codeintel
            - name: EXECUTOR_MAXIMUM_NUM_JOBS
              value: "10"
            - name: SRC_LOG_LEVEL
              value: info
            - name: SRC_LOG_FORMAT
              value: condensed
            - name: SRC_TRACE_LOG
              value: "false"
            - name: EXECUTOR_KUBERNETES_RESOURCE_REQUEST_MEMORY
              value: 1Gi
              # Since the host is 'host.docker.internal', this needs to be true.
            - name: EXECUTOR_DOCKER_ADD_HOST_GATEWAY
              value: "false"
            - name: EXECUTOR_KUBERNETES_NAMESPACE
              value: src-ed654e65e35cf36daa38
            - name: EXECUTOR_KUBERNETES_PERSISTENCE_VOLUME_NAME
              value: sg-executor-codeintel-pvc

            # Useful for debugging.
            - name: KUBERNETES_KEEP_JOBS
              value: "true"
            - name: EXECUTOR_KEEP_WORKSPACES
              value: "true"
          volumeMounts:
            - mountPath: /data
              name: sg-executor-codeintel-volume
      volumes:
        - name: sg-executor-codeintel-volume
          persistentVolumeClaim:
            claimName: sg-executor-codeintel-pvc
```

Verify the changes are correct and apply all resources with `kubectl apply -f .`

## Sync repos and check network traffic
Add the `Gogs` instance as a code host:

TODO: code host image

Verify that it can pull all the repos and sync.

## Check if there are any issues with network


```

**Comment by danieldides** [comment]
# Batch Changes Testing

We can now finally begin testing various features. First, we'll do Batch Changes. There is a little additional setup to be done:

## Configuration
Set the feature flag `native-ssbc-execution` to `true`:
![Screenshot 2023-05-01 at 17 23 36](https://user-images.githubusercontent.com/8784265/235542002-e98cdf9f-a96f-4fd2-bd45-bd143038e421.png)

## Pulling images
The Batch Change spec we will use will use `ubuntu:18.04` as the image, so we'll need to pull and push it to Artifact Registry:
```bash
#!/bin/bash

IMAGE_TO_PULL="sourcegraph/ubuntu:18.04"
REGISTRY_TO_PULL="docker.io"
REGISTRY_TO_PUSH="us-central1-docker.pkg.dev/src-c54bde77ebd01257330e/cloud-internal-images-mirror"
docker pull $REGISTRY_TO_PULL/$IMAGE_TO_PULL --platform=amd64
docker tag $IMAGE_TO_PULL $REGISTRY_TO_PUSH/$IMAGE_TO_PULL
docker push $REGISTRY_TO_PUSH/$IMAGE_TO_PULL
```

## Install `src-cli` locally
Because we deployed `gogs` rather than GitHub/GitLab, we are running an "unsupported" Code Host and need to start the change locally with `src-cli`. Clone the `sourcegraph/src-cli` repo and run `go install ./cmd/src` to install `src` locally.

In the Site Config, first **delete** the entire `email.smtp` section as well as `email.address`. Save. Then generate an Access Token for the `src-cli` and set it in your terminal:
```
export SRC_ENDPOINT=https://executor-testing.sourcegraph.com
export SRC_ACCESS_TOKEN=sgp_abc123whateveritsaid
```

Run `src login` and verify it was successful.

## Run the Batch Change
Save this batch change spec to a file:
```yaml
name: Test
description: Add Hello World to READMEs

# Find the first 100 search results for README files.
# This could yield less than 100 repos/workspaces if some repos contain multiple READMEs.
on:
  - repositoriesMatchingQuery: file:README.md count:100

# In each repository, run this command. Each repository's resulting diff is captured.
steps:
  - run: IFS=$'\n'; echo Hello Worlds | tee -a $(find -name README.md)
    container: us-central1-docker.pkg.dev/src-c54bde77ebd01257330e/cloud-internal-images-mirror/ubuntu:18.04

# Describe the changeset (e.g., GitHub pull request) you want for each repository.
changesetTemplate:
  title: Hello World
  body: My first batch change!
  commit:
    message: Append Hello World to all README.md files
  # Optional: Push the commit to a branch named after this batch change by default.
  branch: ${{ batch_change.name }}
```
Run `src batch remote -f batch-change.yaml -allow-unsupported`. Open the link it provides and wait for completion to finalize. You should see 10 successful executions.
![Screenshot 2023-05-01 at 17 32 43](https://user-images.githubusercontent.com/8784265/235543043-11b9a73b-ae1b-4fa2-93c4-8b911df87cae.png)

If you do a `kubectl get pods` you should also see all the Job step containers.
