### ISSUE TITLE
batches: add fork attribute to changeset template

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#50849]
allow users to specify the fork by adding a fork attribute to the changeset template with the following possibilities as shown in to Adam's prior example below

```yaml
changesetTemplate:
  fork: foo           # forks into the `foo` organisation/user, assuming the
                      # user has permission
  fork: LawnGnome     # forks into the user's namespace as well (assuming the
                      # user is LawnGnome), but explicitly by name
  fork: user          # forks into the user's namespace, same as the current
```

With fork being a string pointing to the owner to fork into, with user being the current user. This is to address permissions errors faced when attempting to creat forks in non accessible repos 

tracked by #33110

**Comment by BolajiOlajide** [comment]
**Question for the batchers** 

How do we differentiate between forks that should be created in a user namespace vs org namespace for the code hosts. 
I think for now we should only support forking to the currently authenticated user's namespace.

**Comment by BolajiOlajide** [comment]
We could make the attribute breakdown more flexible and explicit by allowing the user specify where the fork should be.

```
fork:
  user: adeola
  org: sourcegraph
```

**Comment by courier-new** [comment]
Just catching up on this. I appreciate the consideration you all shared for this during sprint planning, but I'm actually doubtful that this level of specification would help us. My reasoning is 3-fold:
- The concept of "org" namespaces _really_ only maps well to GitHub. GitLab has the closest equivalent with "groups", but the Bitbuckets organize them into "workspaces" or "projects". ADO is the most complicated of all with 3 levels of hierarchy, org > project > repo; there's no concept of forking into a user namespace at all, because repos never belong to users, only projects, and you can't fork into a different org, only a different project in the same org. So in short, I think the language of "org" would be ambiguous at best and straight up problematic at worst. 😅
- This locks us into a binary of user vs. org when realistically we can't actually assume all code hosts will have this sort of distinction for "places a repo can live." ADO already breaks this; there's only one type of namespace on ADO, and it's a "project". If a user ran a spec with
    ```yaml
      fork:
        user: adeola
    ```
    specified, then, it becomes hard to answer the question what _should_ happen for a repo targeted by this batch spec on ADO?
- I'm actually not sure code hosts really care that what "type" namespace you give it as much as was initially suggested in sprint planning, so long as the namespace exists and is a destination the user has permission to create repos in. I dug into the APIs again a bit to refresh my memory (I *am* the resident forks expert here apparently now, after all 😂) and this is what I've found:
  - GitHub seems to care the most about this. On [GitHub](https://docs.github.com/en/rest/repos/forks?apiVersion=2022-11-28#create-a-fork), if you're trying to fork into an org, you better specify it with the `organization` parameter, or else it's going to fail. Omit it and you get a fork in the user's own namespace. Forking to anywhere else can't be done.
  - On [GitLab](https://docs.gitlab.com/ee/api/projects.html#fork-project), you just provide a `namespace_path`. It doesn't care what sort of namespace the path is for.
  - On [Bitbucket Cloud](https://support.atlassian.com/bitbucket-cloud/docs/fork-a-repository/), you just provide the name of the `workspace`. It once again doesn't care what sort of workspace the name refers to.
  - On [Bitbucket Server](https://docs.atlassian.com/bitbucket-server/rest/6.1.1/bitbucket-rest.html#idp156), you provide a project `key`. The user has a personal project with a special key, but it's still just a key that can be passed the same way.
  - On [ADO](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/repositories/create?view=azure-devops-rest-7.0&tabs=HTTP#create-a-fork-of-a-parent-repository), you provide a project `name`. You can only fork a repo into different projects, so there's only one type of resource that this name could refer to.

Upon reflecting about each code host's unique constraints and namespace terminology, then, I want to submit the following proposal for this new schema attribute instead:

```yaml
fork: foo        # forks into the "foo" namespace whether it's a user, org, workspace,
                 # project, shoebox, void, military fortress, or anything else that can
                 # ostensibly hold a repo, assuming the user has permission.
fork: default    # forks into whatever the default namespace would be on a given code
                 # host based on the current PAT. For most code hosts, that will be the
                 # current user's namespace.
```

This schema:
- Avoids division into types of namespaces that aren't reflected by all the code hosts those namespaces exist on
- Doesn't assume user namespaces are an option on every code host (like on ADO where you can't)
- Respects the default fork behavior we have today for customers who feel that's good enough but still want per-batch-change control over when it's leveraged
- Wouldn't require us to modify anything in the code host source logic about the way we pass namespaces to code host API calls
- Would still give us the flexibility to adapt/extend this in the future if we find a future code host has greater fork configuration needs. Or even extend it today to do other cool things like supply a custom fork name template:
  ```yaml
      # custom everything
      fork:
        namespace: foo
        name: sg-bc-{name}

      # default namespace, but custom name
      fork:
        namespace: default
        name: sg-bc-{name}
  ```

@sourcegraph/batchers give this a read and let me know your thoughts. 🙂
