### ISSUE TITLE
grpc: setup buf breaking in CI

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#51054]
### Motivation
As we adopt gRPC as the default way of doing RPCs, it's important to ensure that we don't accidentally change the protobuf / grpc definitions in a forwards or backwards incompatible way (see https://protobuf.dev/overview/, and https://earthly.dev/blog/backward-and-forward-compatibility/ for more details). 

We can help enforce this in CI by using the [buf breaking ](https://buf.build/docs/breaking/usage) command.

#### Examples of backwards incompatible changes 

Removing a field from a message:

Before:

```proto
message User {
  int32 id = 1;
  string name = 2;
  string email = 3;
}
```
After:

```proto
message User {
  int32 id = 1;
  string name = 2;
  // email field removed
}
```

Changing the field number or field type:

Before:

```proto
message User {
  int32 id = 1;
  string name = 2;
}
```
After:
```proto
message User {
  int64 id = 1; // Changed field type from int32 to int64
  string name = 3; // Changed field number from 2 to 3
}
```

Renaming a service, method, or message:

Before:
```proto
service UserService {
  rpc GetUser(GetUserRequest) returns (User) {}
}

message GetUserRequest {
  int32 id = 1;
}

message User {
  int32 id = 1;
  string name = 2;
}
```
After:

```proto
service UserManagementService { // Renamed the service
  rpc FetchUser(GetUserRequest) returns (User) {} // Renamed the method
}

message GetUserRequest {
  int32 id = 1;
}

message UserData { // Renamed the message
  int32 id = 1;
  string name = 2;
}
```
 
Modifying the request or response type of an RPC method:

Before:

```proto
service UserService {
  rpc GetUser(GetUserRequest) returns (User) {}
}

message GetUserRequest {
  int32 id = 1;
}

message User {
  int32 id = 1;
  string name = 2;
}
```
After:

```proto
service UserService {
  rpc GetUser(FetchUserRequest) returns (UserData) {} // Changed request and response types
}

message FetchUserRequest { // New request type
  int32 userId = 1;
}

message UserData { // New response type
  int32 userId = 1;
  string userName = 2;
}
```

### implementation 

In the main sourcegraph/sourcegraph repository, I think we can integrate `buf breaking` as a `sg lint` rule in the same way that similar rules like `buf format` [were implemented](https://github.com/sourcegraph/sourcegraph/pull/47002).

In 3rd party repositories that don't use `sg` (Zoekt), we can use the [buf-breaking-action](https://github.com/bufbuild/buf-breaking-action) that buf provides. This action detects breaking changes in a pull request and automatically creates inline comments under specific lines in the .proto files.

Here's an example configuration to set up the buf-breaking-action in a GitHub Actions pipeline:

```yaml
on: pull_request # Apply to all pull requests
jobs:
  validate-protos:
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
      # Run breaking change detection against the `main` branch
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/acme/weather.git#branch=main'
```

This configuration will detect breaking changes between the Protobuf sources in the current branch and the main branch of the repository.
