### ISSUE TITLE
testing: RFC for declarative test setup for code host scenarios

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#55509]
Create and RFC which discusses using a declarative test setup for our integration tests and E2E tests with regard to code host configuration. 

At a high level the aim is to abstract/simplify the test setup of code hosts so that the test author can concentrate on running a test. Below is a possible declared test setup for Github

```yaml
---
scenario:
  v: 0.1
  name: "Testzor"
  kind: GitHub
  users:
    - admin
    - user1
    - user2
  repos:
    - "r/public":
        access:
          - admin
          - user1
          - user2
        seed:
          template: repos/
    - "r/private1":
        access:
          - user1
    - "r/private2":
        access:
          - user2
    - "r/private3":
        access:
          - user1
          - user2

Sourcegraph:
    codeHost:
         id: "Testzor"
```

The test author would be able to select this scenario as part of their test and receive a `testContext` which contains all the needed attributes and information that would need to utilize this test setup

```json
{
  ScenarioID: "0xDEADBEAF",
  Endpoint: "https://github.host.com",
  Token: "THIS IS MY TOKEN FOR THE HOST",
  sshKey: "ssh-key asdfl;kasdfklasdf",
  users: [
     { Github user 1 }, { Github user 2}
  ],
  teams: [
   { team 1 }, { team 2}
  ],
  org: "Test-Org-1919292",
}
```

The test author would also then not have to worry about tearing down resources appropriately
```go
func TestGithubScenario1(t *testing.T) {
   testCtx := SGTest.Scenario("scenario.yml")
   
  // Author performs tests

  // handles destruction of resources
  testCtx.Done()
}
```
