### ISSUE TITLE
Add `fail fast`flag to batch changes job

### ISSUE THREAD

**Issue by airamare01** [sourcegraph/sourcegraph#55676]
#### Feature request description

Filing this on behalf of https://github.com/sourcegraph/accounts/issues/4681

Add a fail fast flag to a batch job, in the occurrence that a task fails and renders the batch unexecutable completely, then the entire batch fails completely as soon as the task errors.

**Comment by gabtorre** [comment]
Requested by https://github.com/sourcegraph/accounts/issues/8366

**Comment by camdencheek** [comment]
cc @BolajiOlajide, any thoughts on this one?

**Comment by BolajiOlajide** [comment]
It sounds like a fair request, especially for batch changes that take a long time to fail.

I tested with a spec of my own:

```yaml
name: failed-spec
description: testing failures

on: 
  - repository: github.com/sourcegraph-testing/markdowns
  - repository: github.com/sourcegraph-testing/etcd

steps:
  - run: |
      IFS=$'\n'; echo Hello World | tee -a $(find -name README.md)
      sleep 10
    if: ${{ eq repository.name "github.com/sourcegraph-testing/markdowns" }}
    container: alpine:3

  - run: |
      sleep 3
      exit 1
    if: ${{ eq repository.name "github.com/sourcegraph-testing/etcd" }}
    container: alpine:3

changesetTemplate:
  title: Hello World
  body: My first batch change!
  commit:
    message: Append Hello World to all README.md files
  branch: ${{ batch_change.name }}
  fork: true
  ```

And even though one of the steps fail early, batch change continues.


![Image](https://github.com/sourcegraph/sourcegraph/assets/25608335/c5882429-b32a-4b8c-9f46-9d46e28b4df1)
