### ISSUE TITLE
SSBC Spec validation breaks when using outputs

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#57396]
- **Sourcegraph version:** 5.1.9
- **Platform information:** Server side batch changes
#### Steps to reproduce:

1. Create a server side batch change using outputs in a range action.
```
...
    outputs:
      foo:
        value: ${{ step.modified_files }}
...
changesetTemplate:
  body: |
    ${{ range $index, $bar := outputs.foo }}
      - ${{ $bar }}
    ${{ end }} 
```
#### Expected behavior:
The spec validation and execution are expected to run without issues.

#### Actual behavior:
Error:
Validating batch spec template: template: validateBatchSpecTemplate:20: undefined variable "$bar"
![Screenshot 2023-10-05 at 1 29 33 PM](https://github.com/sourcegraph/sourcegraph/assets/69164745/ba583175-34e5-48ad-bc1d-7f2448694622)

It looks like this validation is removing the line with outputs, resulting in the spec below:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@434944e17d371b5246feed4b3c99b9703a9fd15e/-/blob/lib/batches/template/templating.go?L58-68

```
changesetTemplate:
  body: |
     
      - ${{ $bar }}
    ${{ end }} 
```

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by BolajiOlajide** [comment]
Temporary workaround:

```yaml
name: output-test
description: change golang

on:
  - repositoriesMatchingQuery: context:global repo:sourcegraph/sourcegraph file:Dockerfile select:file golang
steps:
  - run: |     
      while read -r dockerfile; do 
        sed -E -i 's/golang/golang:18.18.0/' $dockerfile
      done < <(find . -not -path '*/node_modules/*' -name '*Dockerfile*')
    container: ubuntu:latest

changesetTemplate:
  title: changing golang
  body: |
    ${{ range $index, $hook := steps.modified_files }}
       - ${{ $hook }}
  
    ${{ end }} 
  commit:
    message: my message
  branch: ${{ batch_change.name }}
```

I'm working on a proper solution for this.
