### ISSUE TITLE
Batch spec templating: ${{ repository.branch }} not returning a value in the "steps" field

### ISSUE THREAD

**Issue by noah-berman** [sourcegraph/sourcegraph#59250]
- **Sourcegraph version:** latest
- **Platform information:** Cloud (tested on S2)

#### Steps to reproduce:

1.  Create a batch spec
2. Define a `steps.run` command that references `repository.branch` using templating (`${{ repository.branch}}`) (we list this as supported here: https://sourcegraph.com/docs/batch_changes/references/batch_spec_templating#steps-context)
3. Define a batch change that adds this templated value to a file, for example (or something else where the value should be visible)
4. Compare the results of this with, for example, `repository.name` returns a value as expected

**Comment by camdencheek** [comment]
Hey Noah! A little extra information about the batch spec would be helpful here.

With that, I can try to answer some followup questions: 
- Are they using a repo query or something else?
- Is the query doing anything weird that it could be returning revisions that aren't at the tip of a branch? 
- Could the repos be cloning?

**Comment by noah-berman** [comment]
```
name: morph
description: its morphin time

on:
  - repository: github.com/my/repo

# In each repository, run this command. Each repository's resulting diff is captured.
steps:
  - run: /go/bin/morph -o  -r ${{ repository.name }} -b ${{ repository.branch }}
    container: docker.io/library/morph


# Describe the changeset (e.g., GitHub pull request) you want for each repository.
changesetTemplate:
  title: "this is my title"
  body: |
    This is a description.

  commit:
    author:
      name: Ted Dorfeuille
      email: ted.dorfeuille@reddit.com
    message: "this is my message"

  # Optional: Push the commit to a branch named after this batch change by default.
  branch: ${{ batch_change.name }}

```
