### ISSUE TITLE
repo-conventions: load config for repo conventions to apply from file

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#61152]
Define a config file which allows the following:

A group of rules
- name of the group
- Branch protection rules
  - branch regex and required status checks
- Teams / collaborators that should be added to a team
- Workflows that should be enabled

Then a list of repos where a group of rules should be applied too

```yaml
defualt_rule: security/track
rule: security/track
  branch_protection:
    branch: main
    require_approvals: true
    approval_teams:
      - security
      - dev-infra
  workflows:
    - test
  teams:
    - security
    - dev-infra
  repos:
    - sourcegraph/infrastructure
    - sourcegraph/bfg

rule: security/soc2
  branch_protection:
    branch: main
    require_approvals: true
    approval_teams:
      - security
      - dev-infra
  workflows:
    - test
    - pr-auditor
    - cla-bot
  teams:
    - security
    - dev-infra
  repos:
    - sourcegraph/sourcegraph
    - sourcegraph/cody
```
