### ISSUE TITLE
Implement NetworkPolicy

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9726]
Migrated from https://github.com/sourcegraph/deploy-sourcegraph/issues/213

**From @terinjokes:**

In our Kubernetes cluster, we're heavy users of [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) for both Pod ingress and egress. We'd like to continue this for Sourcegraph, but currently there's none provided as a base.

I can probably brute force Network Policies from error messages, but it might be easier and faster for someone more familiar with the dependencies to properly setup.

------------------

**From @beyang:**

@terinjokes a couple of clarifying questions:
* Is the goal here to enforce a policy on overall ingress/egress traffic between Sourcegraph and the outside world or to enforce a policy on traffic between pods in the Sourcegraph cluster itself?
* If the latter, is the need for a Network Policy due to Sourcegraph being deployed into a cluster that also has non-Sourcegraph pods or just due to a general policy (e.g., "all Kubernetes clusters must have NetworkPolicies that constrain internal network traffic to only what's minimally necessary")
* If due to a general policy, what are the requirements that the set of Network Policies needs to meet. Is there an internal definition you can share?
* Lastly, how urgent of a need is this for you? Does it block any wider rollout / deployment milestone?

------------

**From @terinjokes:**

1. Ideally a policy for both traffic between the pods and the outside word, and pods and other Sourcegraph pods. However, a blanket policy (pods within the namespace are allowed to communicate with other pods in the namespace) might work for the latter, if you don't want to denote the specifics.
2. It's a general policy for us that all deployments have network policies. This is enforced with a network policy that drops all traffic by default.
3. We don't have a formal definition right now. The assumption is be reasonable. (Eg: don't simply define a network policy for 0.0.0.0/0)
4. It's not extremely urgent. I can make my guesses to some policies.

**Comment by slimsag** [comment]
Update: We had another customer request this (https://app.hubspot.com/contacts/2762526/company/554338610/) -- in their case a blanket policy that allows Sourcegraph services to contact other Sourcegraph services (but nothing else in the cluster) was sufficient. This was:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sourcegraph-namespace-allowance
spec:
  # For all pods with the label "deploy: sourcegraph"
  podSelector:
    matchLabels:
      deploy: sourcegraph
  policyTypes:
  - Ingress
  - Egress
  # Allow all traffic from the sourcegraph-production namespace
  # to the sourcegraph-production namespace.
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: sourcegraph-production
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: sourcegraph-production
```

(replace `sourcegraph-production` with the namespace you're deploying Sourcegraph into)

An additional policy was added independently of this one to connect Sourcegraph with the code host in question. Probably this is all we need to add and document here?

Or, we could go much more restrictive and actually enforce pod <-> pod ingress/egress networking but TBH this could be a subtle source of bugs for us because we cannot enforce the same thing in Sourcegraph developer environments easily I think?
